# CMake generated Testfile for 
# Source directory: /Users/tianyangzhao/Codes/MIPSolvers
# Build directory: /Users/tianyangzhao/Codes/MIPSolvers
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[milp_benchmark]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/milp_benchmark_runner" "--smoke" "--no-highs-adapter" "--json" "/Users/tianyangzhao/Codes/MIPSolvers/milp_benchmark_result.json")
set_tests_properties([=[milp_benchmark]=] PROPERTIES  LABELS "benchmark" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;292;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[native_kernel_comparison]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/native_kernel_comparison" "--smoke" "--check" "--time-limit" "60")
set_tests_properties([=[native_kernel_comparison]=] PROPERTIES  LABELS "benchmark" TIMEOUT "600" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;369;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_engine_api]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_engine_api")
set_tests_properties([=[test_engine_api]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;745;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_ipopt_parameter_stability]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_ipopt_parameter_stability")
set_tests_properties([=[test_ipopt_parameter_stability]=] PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;746;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_lp_solver]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_lp_solver")
set_tests_properties([=[test_lp_solver]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;747;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_milp_solver]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_milp_solver")
set_tests_properties([=[test_milp_solver]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;748;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_ipm_solver]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_ipm_solver")
set_tests_properties([=[test_ipm_solver]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;749;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_conic_ipm]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_conic_ipm")
set_tests_properties([=[test_conic_ipm]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;750;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_aml_conic]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_aml_conic")
set_tests_properties([=[test_aml_conic]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;751;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_aml_model]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_aml_model")
set_tests_properties([=[test_aml_model]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;752;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_dual_simplex]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_dual_simplex")
set_tests_properties([=[test_dual_simplex]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;758;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_branch_and_cut]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_branch_and_cut")
set_tests_properties([=[test_branch_and_cut]=] PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;762;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_problem_validation]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_problem_validation")
set_tests_properties([=[test_problem_validation]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;763;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_adapter_registry]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_adapter_registry")
set_tests_properties([=[test_adapter_registry]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;764;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_presolve]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_presolve")
set_tests_properties([=[test_presolve]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;765;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_l2o_trace]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_l2o_trace")
set_tests_properties([=[test_l2o_trace]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;766;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_numerical_stability]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_numerical_stability")
set_tests_properties([=[test_numerical_stability]=] PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;767;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_netlib_regression]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_netlib_regression")
set_tests_properties([=[test_netlib_regression]=] PROPERTIES  LABELS "integration" WORKING_DIRECTORY "/Users/tianyangzhao/Codes/MIPSolvers" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;729;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;768;mipsolvers_add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_scuc_module]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_scuc_module")
set_tests_properties([=[test_scuc_module]=] PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;821;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
add_test([=[test_market_simulation]=] "/Users/tianyangzhao/Codes/MIPSolvers/tests/test_market_simulation")
set_tests_properties([=[test_market_simulation]=] PROPERTIES  LABELS "benchmark" TIMEOUT "600" _BACKTRACE_TRIPLES "/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;843;add_test;/Users/tianyangzhao/Codes/MIPSolvers/CMakeLists.txt;0;")
subdirs("_deps/embedded_highs")
subdirs("_deps/embedded_scip")
subdirs("_deps/fmt_vendored")
