import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const i = process.argv.indexOf('--server');
const exe = i < 0 ? path.join(root, 'build/macos-release/run_gui_server') : process.argv[i + 1];
const port = await new Promise(resolve => { const s = createServer(); s.listen(0, '127.0.0.1', () => { const p = s.address().port; s.close(() => resolve(p)); }); });
const url = `http://127.0.0.1:${port}`;
const server = spawn(exe, ['--host','127.0.0.1','--port',String(port),'--data-dir',path.join(root,'data')], { cwd: root, stdio: 'ignore' });
let browser;
const get = async () => (await fetch(url + '/api/session/market_forecast')).json();
const post = async body => { const r = await fetch(url + '/api/session/market_forecast', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); return { status: r.status, data: await r.json() }; };
try {
  for (let n = 0; n < 100; ++n) { try { if ((await fetch(url + '/api/cases')).ok) break; } catch {} await new Promise(r => setTimeout(r, 100)); }
  browser = await chromium.launch(); const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  await page.addInitScript(() => localStorage.setItem('hysim.tourDone.v1','1'));
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(url + '/xjtu/#market-operation', { waitUntil: 'load' });
  await page.getByLabel('负荷分布', { exact: true }).waitFor({ state: 'visible' });
  await page.locator('#operationCase').selectOption('example'); await page.locator('#operationLoadCase').click();
  await page.waitForFunction(() => document.querySelector('#operationBoundaryName').textContent.includes('南方规则解析算例'));
  await page.locator('#forecastStartDate').fill('2028-02-01'); await page.locator('#forecastStartDate').dispatchEvent('change');
  await page.locator('#forecastCount').fill('4'); await page.locator('#forecastCount').dispatchEvent('change');
  for (const name of ['风电','光伏','来水','发电/储能报价','可控负荷补偿','线路限额']) await page.getByLabel(`${name}分布`,{exact:true}).selectOption('fixed');
  await page.getByLabel('负荷下界',{exact:true}).fill('1'); await page.getByLabel('负荷下界',{exact:true}).dispatchEvent('change');
  await page.getByLabel('负荷上界',{exact:true}).fill('3'); await page.getByLabel('负荷上界',{exact:true}).dispatchEvent('change');
  await page.getByLabel('负荷统一中心',{exact:true}).fill('2'); await page.getByLabel('负荷统一中心',{exact:true}).dispatchEvent('change');
  const capabilities=await (await fetch(url+'/api/session/market_operation')).json();
  const gurobiAvailable=capabilities.solver_capabilities.find(s=>s.id==='gurobi').available;
  if(gurobiAvailable) {
    await page.locator('#forecastSolver').selectOption('gurobi');
    await page.locator('#forecastThreads').fill('2');await page.locator('#forecastThreads').dispatchEvent('change');
    await page.locator('#forecastTimeLimit').fill('30');await page.locator('#forecastTimeLimit').dispatchEvent('change');
  }
  await page.locator('#forecastGenerate').click();
  await page.waitForFunction(() => document.querySelector('#forecastStatus').textContent.includes('边界已生成'));
  let state = await get(); assert.equal(state.job.scenarios.length, 4); assert.equal(state.job.scenarios[0].config.days.length, 8);
  assert.equal(state.job.config.marginals[0].center.length, 8);
  assert.match(await page.locator('#forecastBoundaryPreview').textContent(), /2028-02-08（仅预测）/);
  assert.equal(state.job.config.marginals[0].center[0], 2);
  assert.equal(await page.getByLabel('Canvas 日期', { exact: true }).locator('option').count(), 7);
  assert.equal(await page.locator('#marketCanvas').getAttribute('data-valid'), 'false');
  assert.match(await page.locator('#forecastBoundaryPreview').textContent(), /2028-02-07/);
  await page.getByRole('button',{name:'预览场景当日边界 1',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#forecastRuleBoundaryResolved').textContent.includes('覆盖与扰动后'));
  assert.match(await page.locator('#forecastRuleBoundaryResolved').textContent(),/统调负荷/);
  let invalid = structuredClone(state.job.config); invalid.correlation[0][1] = .5;
  assert.equal((await post({ action: 'generate', revision: state.revision, config: invalid })).status, 400);
  assert.equal((await get()).run_id, state.run_id);
  await page.locator('#forecastRun').click();
  await page.waitForFunction(() => document.querySelector('#forecastStatus').textContent.includes('场景任务结束'), { timeout: 120000 });
  state = await get(); assert.equal(state.job.completed_days, 28); assert.equal(state.job.statistics.complete_scenarios,4);
  if(gurobiAvailable) for(const s of state.job.scenarios) for(const d of s.days) for(const stage of ['scuc','sced','lmp']) assert.equal(d.stages[stage].solver,'Gurobi');
  const energy = state.job.scenarios.map(s => s.config.days.slice(0,7).reduce((v,d) => v + Math.max(0,100*d.load_scale-200)*24,0));
  assert.ok(Math.abs(state.job.statistics.week_deficit_mwh.mean-energy.reduce((a,b)=>a+b,0)/4)<1e-6);
  assert.equal(state.job.statistics.periods.length,672);
  assert.ok((await page.locator('#forecastStatistics').textContent()).includes('Wilson'));
  const affected = state.job.scenarios.find(s => s.days.some(d=>d.deficit_mwh>1)); assert.ok(affected);
  const day = affected.days.find(d=>d.deficit_mwh>1);
  await page.locator('#forecastScenario').selectOption(String(affected.id)); await page.locator('#operationResultDay').selectOption(String(day.day));
  const expected = day.nodes[0].deficit_mw[0]-day.nodes[0].surplus_mw[0];
  assert.ok(Math.abs(Number(await page.locator('[data-market-ref="buses:1"]').getAttribute('data-value'))-expected)<1e-6);
  assert.match(await page.locator('#marketCanvasContext').textContent(), new RegExp(`场景 ${affected.id+1}`));
  await page.getByLabel('Canvas 场景', { exact: true }).selectOption('0');
  const reference = state.job.scenarios[0].days[day.day].nodes[0];
  assert.ok(Math.abs(Number(await page.locator('[data-market-ref="buses:1"]').getAttribute('data-value'))-(reference.deficit_mw[0]-reference.surplus_mw[0]))<1e-6);
  await page.getByLabel('Canvas 场景', { exact: true }).selectOption(String(affected.id));
  assert.match(await page.locator('#operationCauses').textContent(), /恢复因素/);
  assert.ok(day.counterfactuals.some(c=>c.reference_value===2&&c.valid));
  const download = await (await fetch(url+'/api/session/market_forecast?export=1')).json(); assert.equal(download.job.base.buses.length,1);
  await mkdir(path.join(root,'output/market-forecast'),{recursive:true});
  await writeFile(path.join(root,'output/market-forecast/evidence.json'),JSON.stringify(download.job,null,2));
  await page.locator('#forecastStatistics').scrollIntoViewIfNeeded(); await page.screenshot({path:path.join(root,'output/market-forecast/desktop.png')});
  await page.reload({waitUntil:'load'}); await page.waitForFunction(()=>document.querySelector('#forecastStatus').textContent.includes('场景任务结束'));
  assert.equal(await page.locator('#forecastCount').inputValue(),'4');
  await page.setViewportSize({width:390,height:844}); await page.locator('#forecastStatistics').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>document.querySelector('#forecastDeltaPChart .svg-container').clientWidth<=document.querySelector('#forecastDeltaPChart').clientWidth+1);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1));
  await page.screenshot({path:path.join(root,'output/market-forecast/mobile.png')});
  await page.locator('#forecastMode').selectOption('interval');
  await page.locator('#forecastCount').fill('2'); await page.locator('#forecastCount').dispatchEvent('change');
  await page.locator('#forecastGenerate').click(); await page.waitForFunction(()=>document.querySelector('#forecastStatus').textContent.includes('边界已生成'));
  await page.locator('#forecastRun').click(); await page.waitForFunction(()=>document.querySelector('#forecastStatus').textContent.includes('场景任务结束'),{timeout:120000});
  state=await get(); assert.equal(state.job.statistics.week_delta_p_peak_mw.event_probability_valid_only,null);
  assert.match(await page.locator('#forecastStatistics').textContent(),/不是发生概率/);
  const config=state.job.config;
  const start=await post({action:'generate',revision:state.revision,config}); assert.equal(start.status,200);
  assert.equal((await post({action:'step',run_id:start.data.run_id,scenario:0,day:1})).status,409);
  await page.locator('#forecastReload').click(); await page.waitForFunction(()=>!document.querySelector('#forecastCancel').disabled);
  await page.locator('#forecastCancel').click(); await page.waitForFunction(()=>document.querySelector('#forecastStatus').textContent.includes('终止'));
  assert.equal((await get()).job.status,'cancelled');
  assert.equal((await post({action:'step',run_id:start.data.run_id,scenario:0,day:0})).status,400);
  assert.deepEqual(errors,[]);
  console.log('Forecast GUI/API passed: seven-day generation, probabilistic and interval scenarios, daily clearing, analytic statistics, reference causes, export/reload/cancel/conflict, mobile.');
} finally { if(browser) await browser.close(); server.kill(); }
