#include "hacdcpf/model/model_semantics.hpp"

#include <algorithm>
#include <initializer_list>
#include <utility>

namespace hacdcpf::model {
namespace {

using F = RuntimeFidelity;

ComponentRuntimeSemantics component(
    const char* type, const char* path, const char* terminal,
    const char* units, const char* sign, const char* owner,
    const char* result, std::initializer_list<WorkflowFidelity> workflows,
    const char* boundary) {
  return {type,
          path,
          "Stable authored component .index; vector position and graph index are execution-only",
          terminal,
          units,
          sign,
          owner,
          result,
          workflows,
          boundary};
}

WorkflowFidelity wf(const char* workflow, F fidelity, const char* role) {
  return {workflow, fidelity, role};
}

const char* kAcTerminal =
    "AC terminal is an authored AC bus ID and is resolved only through an AC-qualified map";
const char* kDcTerminal =
    "DC terminal is an authored DC bus ID and is resolved only through a DC-qualified map";
const char* kHybridTerminal =
    "Every AC/DC terminal is domain-qualified; equal integer bus IDs do not imply one node";
const char* kAcUnits =
    "Engineering input uses MW/Mvar/kV/deg and explicit per-unit fields on system base_mva";
const char* kDcUnits =
    "Engineering input uses MW/kV and explicit per-unit voltage/resistance on system base_mva";
const char* kPhaseUnits =
    "Per-phase engineering power and phase voltage/angle; impedance matrices declare physical or per-unit basis";
const char* kInjectionSign =
    "Positive P/Q is injection for sources and discharge; positive load P/Q is consumption";
const char* kBranchSign =
    "Terminal flow is positive from the named terminal into the branch; losses are nonnegative consumption";

const std::vector<ComponentRuntimeSemantics>& components() {
  static const std::vector<ComponentRuntimeSemantics> rows = {
      component("ACBus", "ac.buses", kAcTerminal, kAcUnits,
                "pd_mw/qd_mvar are additive positive demand; vm_pu and va_deg are authored state/setpoint seeds",
                "HybridPowerSystem::ac.buses",
                "Voltage vectors use authored bus order after unprojection; units are pu and radians",
                {wf("power_flow", F::Exact, "balanced nodal voltage and additive bus demand"),
                 wf("optimal_power_flow", F::Exact, "balanced nodal state, limits, demand and dual location"),
                 wf("dynamics", F::Equivalent, "positive-sequence seed expanded to phase phasors"),
                 wf("time_series", F::Exact, "snapshot state and fallback bus demand"),
                 wf("reliability_resilience", F::Equivalent, "topology node and served-demand location"),
                 wf("market_carbon", F::Equivalent, "settlement/carbon node")},
                "Balanced and phase-domain equations are distinct; results must identify bus order and domain"),
      component("ACBranch", "ac.branches", kAcTerminal, kAcUnits, kBranchSign,
                "HybridPowerSystem::ac.branches",
                "BranchFlow is restored to authored branch identity and MVA/MW/Mvar terminal semantics",
                {wf("power_flow", F::Exact, "positive-sequence pi branch"),
                 wf("optimal_power_flow", F::Exact, "AC flow or declared DC/linear approximation"),
                 wf("dynamics", F::Equivalent, "balanced branch admittance expanded to phase network"),
                 wf("time_series", F::Exact, "per-snapshot branch"),
                 wf("reliability_resilience", F::Equivalent, "availability and capacity edge"),
                 wf("market_carbon", F::Equivalent, "network constraint and traced-flow edge")},
                "Linearized modules must declare that voltage/reactive/loss physics are reduced"),
      component("Generator", "ac.generators", kAcTerminal, kAcUnits, kInjectionSign,
                "HybridPowerSystem::ac.generators and DynamicModelProfile",
                "Dispatch and dynamic outputs retain stable generator .index and engineering units",
                {wf("power_flow", F::Exact, "P/Q injection, PV/slack controls and Q limits"),
                 wf("optimal_power_flow", F::Exact, "P/Q variables, limits and cost"),
                 wf("dynamics", F::Exact, "selected machine/control DAE model"),
                 wf("time_series", F::Exact, "commitment/dispatch/profile state"),
                 wf("reliability_resilience", F::Equivalent, "available capacity and outage state"),
                 wf("market_carbon", F::Exact, "offer, dispatch and emissions source")},
                "A selected dynamic profile supersedes static generator equations only in transient execution"),
      component("StaticGenerator", "ac.static_generators", kAcTerminal, kAcUnits,
                kInjectionSign, "HybridPowerSystem::ac.static_generators",
                "Stable source ID; static outputs are MW/Mvar and dynamic outputs declare selected profile",
                {wf("power_flow", F::Exact, "scaled constant P/Q injection"),
                 wf("optimal_power_flow", F::Equivalent, "fixed or dispatchable DER injection"),
                 wf("dynamics", F::Equivalent, "profile-selected inverter/aggregate model"),
                 wf("time_series", F::Exact, "profile-scaled DER"),
                 wf("reliability_resilience", F::Equivalent, "DER availability/source role"),
                 wf("market_carbon", F::Exact, "DER dispatch and co2_emission_rate")},
                "Grid-forming flags outside the VSC Norton contract are module-specific aggregate capabilities"),
      component("Load", "ac.loads", kAcTerminal, kAcUnits,
                "Positive p_mw/q_mvar is consumption and is additive with bus demand",
                "HybridPowerSystem::ac.loads",
                "Served/shed load retains stable load ID where available; nodal shedding declares bus index space",
                {wf("power_flow", F::Exact, "scaled constant-power or normalized ZIP demand"),
                 wf("optimal_power_flow", F::Exact, "demand plus optional bus-level shedding"),
                 wf("dynamics", F::Equivalent, "static or selected dynamic load model"),
                 wf("time_series", F::Exact, "profile-scaled component demand"),
                 wf("reliability_resilience", F::Exact, "customer/priority-weighted served demand"),
                 wf("market_carbon", F::Exact, "withdrawal and carbon sink")},
                "Exponential loads without represented exponents fail closed in balanced PF"),
      component("FlexibleLoad", "ac.flexible_loads", kAcTerminal, kAcUnits,
                "Positive baseline power is consumption; positive curtailment reduces it",
                "HybridPowerSystem::ac.flexible_loads", "Stable flexible-load ID and MW schedule",
                {wf("power_flow", F::Aggregated, "projected fixed demand at a snapshot"),
                 wf("optimal_power_flow", F::Equivalent, "bounded demand response"),
                 wf("dynamics", F::Aggregated, "static demand equivalent"),
                 wf("time_series", F::Exact, "intertemporal response schedule"),
                 wf("reliability_resilience", F::Equivalent, "curtailable demand"),
                 wf("market_carbon", F::Equivalent, "responsive demand bid")},
                "Utility/discomfort and rebound constraints are not part of snapshot PF"),
      component("AsymmetricLoad", "ac.asymmetric_loads", kAcTerminal, kPhaseUnits,
                "Positive phase P/Q is consumption", "HybridPowerSystem::ac.asymmetric_loads",
                "Phase results use stable component ID and explicit phase labels",
                {wf("power_flow", F::Aggregated, "balanced path uses summed equivalent demand; phase path is native"),
                 wf("optimal_power_flow", F::Projected, "phase OPF native where supported"),
                 wf("dynamics", F::Equivalent, "phase static load"),
                 wf("time_series", F::Aggregated, "profile scales phase demand"),
                 wf("reliability_resilience", F::Aggregated, "total served demand"),
                 wf("market_carbon", F::Aggregated, "nodal withdrawal")},
                "Balanced analysis discards negative/zero-sequence detail"),
      component("Shunt", "ac.shunts", kAcTerminal, kAcUnits,
                "Positive gs_mw consumes P; bs_mvar follows the authored admittance convention",
                "HybridPowerSystem::ac.shunts", "Stable shunt ID, step and Mvar output",
                {wf("power_flow", F::Exact, "voltage-dependent admittance"),
                 wf("optimal_power_flow", F::Equivalent, "fixed or discrete reactive control"),
                 wf("dynamics", F::Exact, "network admittance"),
                 wf("time_series", F::Exact, "snapshot step"),
                 wf("reliability_resilience", F::Equivalent, "available reactive device"),
                 wf("market_carbon", F::NotApplicable, "no direct market/carbon source")},
                "Modules without discrete controls hold current_step fixed"),
      component("Storage", "ac.storage", kAcTerminal, kAcUnits, kInjectionSign,
                "HybridPowerSystem::ac.storage", "Stable storage ID; P/Q, SOC, SOH and energy carry explicit units",
                {wf("power_flow", F::Exact, "fixed snapshot P/Q injection"),
                 wf("optimal_power_flow", F::Equivalent, "bounded charge/discharge and optional SOC"),
                 wf("dynamics", F::Equivalent, "selected storage/converter profile"),
                 wf("time_series", F::Exact, "SOC, efficiency and degradation state"),
                 wf("reliability_resilience", F::Equivalent, "availability, black-start and mobile energy"),
                 wf("market_carbon", F::Equivalent, "charge/discharge bid and stored-carbon state")},
                "Snapshot PF does not certify intertemporal SOC feasibility"),
      component("RenewableGen", "ac.renewable_gens", kAcTerminal, kAcUnits,
                kInjectionSign, "HybridPowerSystem::ac.renewable_gens",
                "Stable renewable ID; available, dispatched and curtailed MW are distinct",
                {wf("power_flow", F::Exact, "fixed P/Q injection"),
                 wf("optimal_power_flow", F::Equivalent, "bounded curtailment"),
                 wf("dynamics", F::Equivalent, "aggregate renewable profile"),
                 wf("time_series", F::Exact, "weather/profile availability"),
                 wf("reliability_resilience", F::Equivalent, "scenario-dependent available source"),
                 wf("market_carbon", F::Exact, "zero/offset emission source and curtailment cost")},
                "Weather-to-power conversion may be exogenous to the electrical solve"),
      component("PVSystem", "ac.pv_systems", kAcTerminal, kAcUnits,
                kInjectionSign, "HybridPowerSystem::ac.pv_systems",
                "Stable PV ID; DC-array and AC-inverter quantities remain distinguished",
                {wf("power_flow", F::Equivalent, "PV curve or authored P/Q injection"),
                 wf("optimal_power_flow", F::Equivalent, "inverter capability/curtailment"),
                 wf("dynamics", F::Equivalent, "selected inverter profile"),
                 wf("time_series", F::Exact, "irradiance/profile-driven production"),
                 wf("reliability_resilience", F::Equivalent, "available DER source"),
                 wf("market_carbon", F::Equivalent, "renewable injection")},
                "Balanced snapshot does not solve the detailed DC array IV curve dynamically"),
      component("ExternalGrid", "ac.external_grids", kAcTerminal, kAcUnits,
                kInjectionSign, "HybridPowerSystem::ac.external_grids",
                "Stable source ID; slack exchange and emission factor use engineering units",
                {wf("power_flow", F::Exact, "terminal voltage-angle reference"),
                 wf("optimal_power_flow", F::Equivalent, "bounded/unbounded grid exchange"),
                 wf("dynamics", F::Equivalent, "Thevenin/infinite-bus source"),
                 wf("time_series", F::Exact, "grid exchange boundary"),
                 wf("reliability_resilience", F::Exact, "upstream supply availability"),
                 wf("market_carbon", F::Exact, "price/emission boundary")},
                "An external grid is a physical source; a bare SLACK bus is not"),
      component("Transformer2W", "ac.transformers_2w", kAcTerminal, kAcUnits,
                kBranchSign, "HybridPowerSystem::ac.transformers_2w",
                "Transformer result is attributed to stable authored ID after branch projection",
                {wf("power_flow", F::Projected, "equivalent tap/shift branch"),
                 wf("optimal_power_flow", F::Projected, "branch and optional tap control"),
                 wf("dynamics", F::Equivalent, "network transformer admittance"),
                 wf("time_series", F::Projected, "snapshot tap"),
                 wf("reliability_resilience", F::Exact, "asset outage/topology identity"),
                 wf("market_carbon", F::Equivalent, "network edge")},
                "Magnetizing and connection detail depend on the selected balanced/phase model"),
      component("Transformer3W", "ac.transformers_3w", kAcTerminal, kAcUnits,
                kBranchSign, "HybridPowerSystem::ac.transformers_3w",
                "Multiple canonical branches map back to one stable transformer ID",
                {wf("power_flow", F::Projected, "pairwise/star equivalent branches"),
                 wf("optimal_power_flow", F::Projected, "equivalent branch constraints"),
                 wf("dynamics", F::Equivalent, "network equivalent"),
                 wf("time_series", F::Projected, "snapshot equivalent"),
                 wf("reliability_resilience", F::Exact, "single asset outage identity"),
                 wf("market_carbon", F::Equivalent, "network edges")},
                "Per-winding result recovery requires the projection map and participation law"),
      component("RegulatorControl", "ac.regulator_controls", kAcTerminal,
                kAcUnits, "Tap increase follows authored winding convention",
                "HybridPowerSystem::ac.regulator_controls", "Stable control ID, monitored bus and tap action",
                {wf("power_flow", F::Exact, "distribution-PF regulator loop where supported"),
                 wf("optimal_power_flow", F::Equivalent, "discrete/relaxed tap control"),
                 wf("dynamics", F::Unsupported, "fast regulator sequence is outside transient runtime"),
                 wf("time_series", F::Equivalent, "per-step tap action"),
                 wf("reliability_resilience", F::Equivalent, "control availability"),
                 wf("market_carbon", F::NotApplicable, "no direct source/sink")},
                "Remote sensing/LDC coverage is solver-specific and must fail closed when unsupported"),
      component("Switch", "ac.switches", kAcTerminal, kAcUnits, kBranchSign,
                "HybridPowerSystem::ac.switches", "Stable switch ID and terminal flow recovered after contraction",
                {wf("power_flow", F::Projected, "closed contraction/open disconnection"),
                 wf("optimal_power_flow", F::Projected, "fixed or binary topology"),
                 wf("dynamics", F::Exact, "event-controlled connectivity"),
                 wf("time_series", F::Exact, "snapshot state"),
                 wf("reliability_resilience", F::Exact, "switching action and availability"),
                 wf("market_carbon", F::Equivalent, "topology edge")},
                "Zero-impedance contraction must preserve BranchExpandMap result recovery"),
      component("CircuitBreaker", "ac.circuit_breakers", kAcTerminal, kAcUnits,
                kBranchSign, "HybridPowerSystem::ac.circuit_breakers",
                "Stable breaker ID and terminal flow recovered after contraction",
                {wf("power_flow", F::Projected, "closed contraction/open disconnection"),
                 wf("optimal_power_flow", F::Projected, "fixed topology"),
                 wf("dynamics", F::Exact, "breaker event"),
                 wf("time_series", F::Exact, "snapshot state"),
                 wf("reliability_resilience", F::Exact, "protection/switching asset"),
                 wf("market_carbon", F::Equivalent, "topology edge")},
                "Protection timing is not represented by steady-state contraction"),
      component("ChargingStation", "ac.charging_stations", kAcTerminal, kAcUnits,
                "Positive charging P/Q is consumption", "HybridPowerSystem::ac.charging_stations",
                "Stable station ID; site power and charger attribution remain separate",
                {wf("power_flow", F::Aggregated, "site demand"),
                 wf("optimal_power_flow", F::Equivalent, "bounded/flexible site demand"),
                 wf("dynamics", F::Aggregated, "static demand"),
                 wf("time_series", F::Exact, "arrival/charging schedule"),
                 wf("reliability_resilience", F::Equivalent, "served transport-energy demand"),
                 wf("market_carbon", F::Equivalent, "responsive demand/carbon sink")},
                "Individual vehicle/charger constraints are outside snapshot PF"),
      component("Charger", "ac.chargers", kAcTerminal, kAcUnits,
                "Positive charging power is consumption", "HybridPowerSystem::ac.chargers",
                "Stable charger ID maps through its station; site totals must not duplicate charger demand",
                {wf("power_flow", F::Aggregated, "rolled into charging station"),
                 wf("optimal_power_flow", F::Aggregated, "station capacity"),
                 wf("dynamics", F::Aggregated, "static site demand"),
                 wf("time_series", F::Exact, "charger schedule"),
                 wf("reliability_resilience", F::Equivalent, "charger availability"),
                 wf("market_carbon", F::Aggregated, "station withdrawal")},
                "Station aggregation owns the no-double-counting rule"),
      component("AsynchronousMotor", "ac.motors", kAcTerminal, kAcUnits,
                "Positive electrical P/Q is consumption; mechanical output sign is profile-defined",
                "HybridPowerSystem::ac.motors and DynamicModelProfile",
                "Stable motor ID; static demand and dynamic states are separate results",
                {wf("power_flow", F::Aggregated, "equivalent demand"),
                 wf("optimal_power_flow", F::Aggregated, "fixed demand"),
                 wf("dynamics", F::Exact, "selected induction motor DAE"),
                 wf("time_series", F::Aggregated, "availability/load profile"),
                 wf("reliability_resilience", F::Equivalent, "critical load asset"),
                 wf("market_carbon", F::Aggregated, "nodal withdrawal")},
                "Static equivalent cannot certify stall/reacceleration behavior"),
      component("DCBus", "dc.buses", kDcTerminal, kDcUnits,
                "pd_mw is additive positive DC demand; vm_pu is DC pole voltage magnitude",
                "HybridPowerSystem::dc.buses", "DC voltage vector uses authored DC bus order after projection",
                {wf("power_flow", F::Exact, "DC nodal voltage/power balance"),
                 wf("optimal_power_flow", F::Equivalent, "DC voltage or linearized balance"),
                 wf("dynamics", F::Equivalent, "DC-link algebraic node"),
                 wf("time_series", F::Exact, "snapshot DC state"),
                 wf("reliability_resilience", F::Equivalent, "DC topology/load node"),
                 wf("market_carbon", F::Equivalent, "DC settlement/carbon node")},
                "DC_V typing requires a physical voltage-forming source for strict coordination"),
      component("DCBranch", "dc.branches", kDcTerminal, kDcUnits, kBranchSign,
                "HybridPowerSystem::dc.branches", "Stable DC branch ID and MW/current direction",
                {wf("power_flow", F::Exact, "resistive DC branch"),
                 wf("optimal_power_flow", F::Equivalent, "DC network constraint"),
                 wf("dynamics", F::Exact, "algebraic DC conductance"),
                 wf("time_series", F::Exact, "snapshot branch"),
                 wf("reliability_resilience", F::Exact, "DC asset outage/topology"),
                 wf("market_carbon", F::Equivalent, "DC network/tracing edge")},
                "Pole configuration and electromagnetic cable dynamics are outside the resistive model"),
      component("DCLoad", "dc.loads", kDcTerminal, kDcUnits,
                "Positive p_mw is DC consumption and is additive with DCBus::pd_mw",
                "HybridPowerSystem::dc.loads", "Stable DC load ID; served/shed energy uses MW/MWh",
                {wf("power_flow", F::Exact, "scaled constant-power/ZIP subset"),
                 wf("optimal_power_flow", F::Equivalent, "demand and shedding"),
                 wf("dynamics", F::Equivalent, "DC algebraic load"),
                 wf("time_series", F::Exact, "profile demand"),
                 wf("reliability_resilience", F::Exact, "customer/priority demand"),
                 wf("market_carbon", F::Exact, "DC withdrawal/carbon sink")},
                "Consumer modules must include both bus-level and component-level DC demand exactly once"),
      component("Storage", "dc.storage", kDcTerminal, kDcUnits, kInjectionSign,
                "HybridPowerSystem::dc.storage legacy execution schema",
                "Stable storage ID; q_mvar must remain zero in DC execution",
                {wf("power_flow", F::Exact, "active-power injection"),
                 wf("optimal_power_flow", F::Equivalent, "DC charge/discharge"),
                 wf("dynamics", F::Equivalent, "DC source/storage profile"),
                 wf("time_series", F::Exact, "SOC and efficiency"),
                 wf("reliability_resilience", F::Equivalent, "DC energy availability"),
                 wf("market_carbon", F::Equivalent, "bid and stored carbon")},
                "Legacy Storage is an execution view; persistent new data should use DCStorage"),
      component("DCStorage", "dc.dc_storage", kDcTerminal, kDcUnits,
                kInjectionSign, "HybridPowerSystem::dc.dc_storage",
                "Stable DCStorage ID materializes to Storage with q=0 and identical shared fields",
                {wf("power_flow", F::Projected, "shared DC storage execution view"),
                 wf("optimal_power_flow", F::Projected, "shared DC storage execution view"),
                 wf("dynamics", F::Projected, "shared DC storage execution view"),
                 wf("time_series", F::Projected, "shared SOC execution view"),
                 wf("reliability_resilience", F::Projected, "shared availability view"),
                 wf("market_carbon", F::Projected, "shared bid/carbon view")},
                "materialize_dc_storage is the sole field-precedence rule and clears the source table in execution copies"),
      component("StaticGenerator", "dc.static_generators", kDcTerminal, kDcUnits,
                kInjectionSign, "HybridPowerSystem::dc.static_generators legacy execution schema",
                "Stable source ID; q_mvar has no DC-network effect",
                {wf("power_flow", F::Exact, "scaled active-power injection"),
                 wf("optimal_power_flow", F::Equivalent, "fixed/dispatchable DC source"),
                 wf("dynamics", F::Equivalent, "DC source profile"),
                 wf("time_series", F::Exact, "profile-scaled source"),
                 wf("reliability_resilience", F::Equivalent, "available source"),
                 wf("market_carbon", F::Exact, "cost and emission source")},
                "Legacy StaticGenerator is retained for compatibility; persistent native type is StaticGeneratorDC"),
      component("StaticGeneratorDC", "dc.dc_static_generators", kDcTerminal,
                kDcUnits, kInjectionSign, "HybridPowerSystem::dc.dc_static_generators",
                "Stable native ID; PF execution view maps p_set_mw to p_mw and emission factor to co2_emission_rate",
                {wf("power_flow", F::Projected, "active-power injection view"),
                 wf("optimal_power_flow", F::Equivalent, "native DC source limits/cost"),
                 wf("dynamics", F::Exact, "native dynamic profile where supported"),
                 wf("time_series", F::Exact, "native profile_id/source"),
                 wf("reliability_resilience", F::Exact, "native reliability fields"),
                 wf("market_carbon", F::Exact, "native cost/emission source")},
                "PF injection view intentionally omits type/profile/reliability/dynamic metadata; rich model remains authoritative"),
      component("PVArrayDC", "dc.pv_arrays", kDcTerminal, kDcUnits,
                kInjectionSign, "HybridPowerSystem::dc.pv_arrays",
                "Stable DC array ID; p_set_mw and IV parameters are not interchangeable",
                {wf("power_flow", F::Equivalent, "authored active-power injection"),
                 wf("optimal_power_flow", F::Equivalent, "bounded renewable injection"),
                 wf("dynamics", F::Equivalent, "selected DC source profile"),
                 wf("time_series", F::Exact, "irradiance/temperature availability"),
                 wf("reliability_resilience", F::Equivalent, "available source"),
                 wf("market_carbon", F::Equivalent, "renewable DC source")},
                "Snapshot electrical solve does not solve a detailed nonlinear IV curve"),
      component("DCDCConverter", "dc.dcdc_converters", kDcTerminal, kDcUnits,
                "Positive transfer follows bus_in to bus_out convention; losses consume power",
                "HybridPowerSystem::dc.dcdc_converters", "Stable converter ID, terminal buses, MW transfer and loss",
                {wf("power_flow", F::Exact, "bidirectional power/loss transfer"),
                 wf("optimal_power_flow", F::Equivalent, "bounded transfer and efficiency"),
                 wf("dynamics", F::Equivalent, "DC converter algebraic/dynamic profile"),
                 wf("time_series", F::Exact, "snapshot transfer"),
                 wf("reliability_resilience", F::Exact, "asset availability/topology"),
                 wf("market_carbon", F::Equivalent, "DC transfer edge")},
                "Duty-ratio and switching dynamics require explicit model_scope flags"),
      component("DCCircuitBreaker", "dc.dc_circuit_breakers", kDcTerminal,
                kDcUnits, kBranchSign, "HybridPowerSystem::dc.dc_circuit_breakers",
                "Stable breaker ID and state; result terminal direction is explicit",
                {wf("power_flow", F::Projected, "closed connectivity/open disconnection"),
                 wf("optimal_power_flow", F::Projected, "fixed topology"),
                 wf("dynamics", F::Exact, "breaker event"),
                 wf("time_series", F::Exact, "snapshot state"),
                 wf("reliability_resilience", F::Exact, "protection/topology asset"),
                 wf("market_carbon", F::Equivalent, "DC topology edge")},
                "Arc/interruption physics are outside steady-state topology"),
      component("VSCConverter", "vsc_converters", kHybridTerminal, kAcUnits,
                "p_set_mw/q_set_mvar are AC-side injection commands; DC injection uses declared efficiency/loss direction",
                "HybridPowerSystem::vsc_converters and resolve_gfm_norton_parameters",
                "VSCTransfer/VSCLimitStateResult retain stable converter and domain-qualified terminal IDs",
                {wf("power_flow", F::Exact, "explicit local AC/DC variables, loss, controls and optional GFM/NCP block"),
                 wf("optimal_power_flow", F::Equivalent, "dispatch/capability constraints followed by PF replay certificate"),
                 wf("dynamics", F::Equivalent, "selected converter DAE seeded by stable-ID PF certificate"),
                 wf("time_series", F::Exact, "authored mode retained; per-step PF certificate"),
                 wf("reliability_resilience", F::Equivalent, "available transfer/control asset"),
                 wf("market_carbon", F::Equivalent, "bidirectional transfer and loss")},
                "Balanced OPF does not claim endogenous GFM NCP; phase and transient equations have separate validity scopes"),
      component("LCCConverter", "lcc_converters", kHybridTerminal, kAcUnits,
                "AC/DC transfer direction and loss follow the authored rectifier/inverter convention",
                "HybridPowerSystem::lcc_converters", "Stable station ID, AC/DC terminals, MW/Mvar, current and angle",
                {wf("power_flow", F::Equivalent, "quasi-steady LCC equations and optional tap control"),
                 wf("optimal_power_flow", F::Equivalent, "shared quasi-steady constraints"),
                 wf("dynamics", F::Unsupported, "full commutation transient is not represented"),
                 wf("time_series", F::Equivalent, "quasi-steady snapshots"),
                 wf("reliability_resilience", F::Equivalent, "station availability/transfer"),
                 wf("market_carbon", F::Equivalent, "HVDC transfer/loss")},
                "Commutation overlap/failure coverage is quasi-steady and must be disclosed"),
      component("EnergyRouter", "energy_routers", kHybridTerminal, kAcUnits,
                "Each port declares injection direction in its own domain",
                "HybridPowerSystem::energy_routers", "Stable router/port identity maps to expanded primitive results",
                {wf("power_flow", F::Projected, "expanded VSC/DC-DC primitives"),
                 wf("optimal_power_flow", F::Projected, "expanded routing/transfer constraints"),
                 wf("dynamics", F::Equivalent, "expanded port devices"),
                 wf("time_series", F::Projected, "port schedules"),
                 wf("reliability_resilience", F::Equivalent, "multi-port asset availability"),
                 wf("market_carbon", F::Equivalent, "multi-carrier electrical exchange")},
                "Expansion mappings own attribution; primitive vector positions are never router IDs"),
      component("MobileStorage", "mobile_storage", kHybridTerminal, kAcUnits,
                kInjectionSign, "HybridPowerSystem::mobile_storage",
                "Stable mobile asset ID plus current location/time; electrical result uses connected bus",
                {wf("power_flow", F::Projected, "connected Storage equivalent; no injection in transit"),
                 wf("optimal_power_flow", F::Equivalent, "location-conditioned charge/discharge"),
                 wf("dynamics", F::Equivalent, "connected storage profile"),
                 wf("time_series", F::Exact, "route/location/SOC state"),
                 wf("reliability_resilience", F::Exact, "routing and restoration energy"),
                 wf("market_carbon", F::Equivalent, "location-conditioned bid/carbon")},
                "A result must include time/location before electrical bus attribution is meaningful"),
      component("VirtualPowerPlant", "vpps", kAcTerminal, kAcUnits,
                kInjectionSign, "HybridPowerSystem::vpps", "Stable VPP ID, PCC bus and aggregate schedule",
                {wf("power_flow", F::Projected, "PCC injection"),
                 wf("optimal_power_flow", F::Equivalent, "aggregate capability"),
                 wf("dynamics", F::Equivalent, "aggregate profile"),
                 wf("time_series", F::Exact, "fleet schedule"),
                 wf("reliability_resilience", F::Equivalent, "aggregate availability"),
                 wf("market_carbon", F::Exact, "participant offer/settlement")},
                "PCC aggregate results cannot be assigned to internal assets without a participation map"),
      component("Microgrid", "microgrids", kAcTerminal, kAcUnits,
                kInjectionSign, "HybridPowerSystem::microgrids", "Stable microgrid ID, PCC and internal bus list",
                {wf("power_flow", F::Projected, "PCC exchange and internal topology where explicitly modelled"),
                 wf("optimal_power_flow", F::Equivalent, "aggregate/internal dispatch by formulation"),
                 wf("dynamics", F::Equivalent, "island frequency/source devices"),
                 wf("time_series", F::Exact, "operating-mode schedule"),
                 wf("reliability_resilience", F::Exact, "islanding/restoration capability"),
                 wf("market_carbon", F::Equivalent, "PCC participant exchange")},
                "Microgrid container metadata is not itself an electrical voltage source"),
      component("ThreePhaseACBus", "three_phase_ac.buses", kAcTerminal,
                kPhaseUnits, "Per-phase demand is positive consumption",
                "HybridPowerSystem::three_phase_ac.buses", "Phase-labelled voltage vectors keyed by stable bus ID",
                {wf("power_flow", F::Exact, "phase-node voltage state"),
                 wf("optimal_power_flow", F::Exact, "phase-node state/limits where phase OPF is selected"),
                 wf("dynamics", F::Exact, "phase network node"),
                 wf("time_series", F::Equivalent, "phase snapshots"),
                 wf("reliability_resilience", F::Equivalent, "phase-aware topology where supported"),
                 wf("market_carbon", F::Aggregated, "balanced settlement/carbon node")},
                "Balanced consumers require an explicit positive-sequence/aggregate projection"),
      component("ThreePhaseACLine", "three_phase_ac.lines", kAcTerminal,
                kPhaseUnits, kBranchSign, "HybridPowerSystem::three_phase_ac.lines",
                "Stable line ID with phase-labelled terminal flows",
                {wf("power_flow", F::Exact, "phase impedance/admittance matrices"),
                 wf("optimal_power_flow", F::Equivalent, "phase flow constraints"),
                 wf("dynamics", F::Exact, "phase network admittance"),
                 wf("time_series", F::Equivalent, "phase snapshots"),
                 wf("reliability_resilience", F::Equivalent, "phase asset/topology"),
                 wf("market_carbon", F::Aggregated, "balanced edge")},
                "Sequence/balanced projection loses mutual and unbalance detail"),
      component("ThreePhaseTransformer", "three_phase_ac.transformers",
                kAcTerminal, kPhaseUnits, kBranchSign,
                "HybridPowerSystem::three_phase_ac.transformers",
                "Stable transformer ID with winding/phase-labelled results",
                {wf("power_flow", F::Exact, "connection-aware phase transformer"),
                 wf("optimal_power_flow", F::Equivalent, "phase transformer constraints"),
                 wf("dynamics", F::Exact, "phase network transformer"),
                 wf("time_series", F::Equivalent, "phase snapshots"),
                 wf("reliability_resilience", F::Exact, "single asset identity"),
                 wf("market_carbon", F::Aggregated, "balanced edge")},
                "Balanced projection cannot preserve all vector-group and zero-sequence behavior"),
      component("ThreePhaseLoad", "three_phase_ac.loads", kAcTerminal,
                kPhaseUnits, "Positive phase P/Q is consumption",
                "HybridPowerSystem::three_phase_ac.loads", "Stable load ID and phase-labelled served power",
                {wf("power_flow", F::Exact, "per-phase ZIP/connection load"),
                 wf("optimal_power_flow", F::Equivalent, "phase demand/shedding"),
                 wf("dynamics", F::Equivalent, "phase static/dynamic load"),
                 wf("time_series", F::Exact, "phase profile demand"),
                 wf("reliability_resilience", F::Equivalent, "served phase demand"),
                 wf("market_carbon", F::Aggregated, "balanced withdrawal")},
                "Balanced aggregation must disclose loss of phase identity"),
      component("ThreePhaseGenerator", "three_phase_ac.generators",
                kAcTerminal, kPhaseUnits, kInjectionSign,
                "HybridPowerSystem::three_phase_ac.generators",
                "Stable generator ID and phase-labelled injection/control result",
                {wf("power_flow", F::Exact, "phase source/control"),
                 wf("optimal_power_flow", F::Equivalent, "phase dispatch/capability"),
                 wf("dynamics", F::Equivalent, "selected source profile"),
                 wf("time_series", F::Exact, "phase schedule"),
                 wf("reliability_resilience", F::Equivalent, "phase source availability"),
                 wf("market_carbon", F::Aggregated, "balanced dispatch/emissions")},
                "Balanced projection must not claim phase current or VUF certification"),
      component("ThreePhaseExternalGrid", "three_phase_ac.external_grids",
                kAcTerminal, kPhaseUnits, kInjectionSign,
                "HybridPowerSystem::three_phase_ac.external_grids",
                "Stable source ID and phase/sequence Thevenin quantities",
                {wf("power_flow", F::Exact, "phase voltage reference"),
                 wf("optimal_power_flow", F::Equivalent, "phase boundary"),
                 wf("dynamics", F::Exact, "phase Thevenin source"),
                 wf("time_series", F::Exact, "boundary state"),
                 wf("reliability_resilience", F::Exact, "upstream source availability"),
                 wf("market_carbon", F::Aggregated, "balanced boundary")},
                "Positive-sequence reduction does not preserve unbalanced source impedance"),
      component("ThreePhaseRegulatorControl", "three_phase_ac.regulator_controls",
                kAcTerminal, kPhaseUnits, "Tap direction follows selected winding and phase",
                "HybridPowerSystem::three_phase_ac.regulator_controls",
                "Stable control ID, monitored phase/bus and tap action",
                {wf("power_flow", F::Exact, "phase regulator control loop"),
                 wf("optimal_power_flow", F::Equivalent, "discrete/relaxed phase tap"),
                 wf("dynamics", F::Unsupported, "fast control sequence outside current DAE"),
                 wf("time_series", F::Equivalent, "per-step tap action"),
                 wf("reliability_resilience", F::Equivalent, "control availability"),
                 wf("market_carbon", F::NotApplicable, "no direct source/sink")},
                "Unsupported remote/LDC/reversible modes must fail closed rather than silently localize control"),
  };
  return rows;
}

const std::vector<ModuleDataContract>& modules() {
  static const std::vector<ModuleDataContract> rows = {
      {"analysis", "Rich model plus analysis options", "Analysis-specific canonical/optimization views", "Typed hosting/counterfactual/weak-link results with model scope", "Stable component and domain-qualified bus IDs after attribution", "Engineering units declared by each result", "Each analysis declares approximation and unsupported assets"},
      {"api", "Validated rich model and public options", "Facade-owned projection/cache/session", "Public typed Result or analysis result", "Authored ordering and stable IDs", "Public engineering units; PF angle output is radians", "Facade must preserve native diagnostics and validity flags"},
      {"carbon_analysis", "Rich model, dispatch/flow snapshots and emission factors", "Domain-qualified carbon-flow graph", "tCO2, tCO2/MWh and GEC results", "Stable source/load and AC/DC bus IDs", "tCO2, tCO2/MWh, MWh", "Approximate or missing physical flows are declared"},
      {"dynamics", "Canonical rich model, DynamicModelProfile and optional PF certificate", "Phase-domain DAE device/network state", "Time-indexed states, device outputs and initialization certificate", "Stable component IDs plus phase/DC positions internal only", "pu, MW/Mvar, Hz, seconds", "Static PF seed, dynamic trim and model-profile overrides are separately certified"},
      {"ev_power_traffic", "Rich electrical model plus traffic network/scenarios", "CTM/LTM and electrical optimization views", "Traffic, charging, welfare and siting results", "Stable station/charger/bus and road IDs", "MW/MWh, vehicles/hour, time and currency", "Electrical and traffic approximations are formulation-labelled"},
      {"graph", "Rich topology with domain-qualified terminals", "Graph node/edge positions and contraction/reduction maps", "Topology reports and recoverable reduced results", "Stable IDs only after mapping; graph positions are private", "Topology is unitless; recovered flows keep source units", "Reduction/contraction must retain provenance and recovery class"},
      {"harmonics_power_flow", "Rich model plus harmonic spectra and operating point", "Frequency-indexed AC/DC admittance models", "Harmonic voltages/currents, THD and standards checks", "Stable bus/branch/source IDs with harmonic order", "pu or engineering units explicitly tagged", "Unsupported nonlinear/time-domain couplings appear in model_limitations"},
      {"integrated_energy", "Campus electric/heat/hydrogen assets and profiles", "Multi-carrier MILP", "Carrier schedules, costs and balance diagnostics", "Stable asset/carrier IDs and aggregate PCC", "MW/MWh, thermal/hydrogen units and currency", "Electrical network may be aggregate PCC rather than nodal AC/DC"},
      {"io", "External schema or rich model", "Format-specific adapter plus provenance report", "Rich model, external artifact and diagnostics", "Stable IDs where format supports them; mappings otherwise", "Conversions declare source/target units", "component_io_mappings is authoritative for lossiness"},
      {"market", "Rich assets, bids, scenarios and network options", "SCUC/SCED/security/settlement models", "Dispatch, LMP, settlement and MarketModelScope", "Stable participant/unit/bus IDs", "MW/MWh, currency/MWh and currency", "AC-only, hybrid linearization and fallback policies are explicit"},
      {"model", "Authored component PODs", "Validation, aggregation and canonical projection", "Canonical model and mapping certificates", "Component .index distinct from vector/graph positions", "Field names carry units; base_mva owns pu conversion", "Only this layer owns persistent physical parameter meaning"},
      {"network_reconfiguration", "Rich topology, switch states, faults and objectives", "Canonical graph and MILP/heuristic topology view", "Switch plan, objective and PF verification", "Stable switch/branch/bus IDs via maps", "MW/Mvar, losses, reliability indices", "Linear network decisions require nonlinear PF verification when claimed"},
      {"optimal_power_flow", "Rich model, costs/limits and OPF options", "SolverData, AML/parity/native/phase optimization variables", "OPFResult with audit, scope, limitations and replay state", "Stable device IDs; bus vectors declare authored/canonical space", "MW/Mvar, pu, currency and dual units", "Balanced GFM NCP is post-PF certified, not an endogenous OPF claim"},
      {"power_flow", "Validated rich or declared canonical model", "SolverData and solver-local sparse/NCP state", "PowerFlowResult and physical flow/certificate projections", "Authored bus order and stable component IDs after unprojection", "pu state/residuals; MW/Mvar public transfers; radians for va", "Every non-Newton/linear/phase variant declares its model scope"},
      {"power_models", "Canonical/rich data plus formulation options", "MIPSolvers AML variables and constraints", "Build result, variables and model limitations", "Stable IDs through explicit index maps", "Per-unit internal with engineering-unit result conversion", "Experimental builders cannot present themselves as production runtime"},
      {"reliability", "Rich assets, failure catalog and scenarios", "FMEA, MC and AC/DC restoration/OPF views", "Indices, event records, served load and model scope", "Stable asset/customer and domain-qualified bus IDs", "hours, events/year, MW/MWh and currency", "AC-only and hybrid evaluators remain distinguishable"},
      {"resilience", "Rich topology/assets, hazards, repair and mobile resources", "Heuristic or staged/multiperiod MIP plus optional DAE oracle", "Restoration trajectory, actions and certification", "Stable component/bus/route IDs", "MW/MWh, time and objective units", "Master-model feasibility and nonlinear/dynamic executability are separate certificates"},
      {"scenario_generation", "Rich assets, distributions, weather and seeds", "Scenario samplers and hazard fields", "Scenario sets with probability/seed/provenance", "Stable asset/location IDs", "Native physical/statistical units", "Fallback distributions and correlations are declared"},
      {"server", "HTTP JSON validated into public API/rich model", "Session/revision/cache and serializer DTOs", "Versioned JSON schema with diagnostics", "Stable IDs and explicit canvas references", "Every vector/quantity carries documented units", "Serializer parity with typed results is executable-test guarded"},
      {"short_circuit", "Rich network, source impedances and fault options", "IEC 60909/sequence/DC fault equivalent", "Fault current, power and contribution results", "Stable faulted bus/source/branch IDs", "kA, MVA, pu and angles", "Simplified sequence/DC assumptions are disclosed"},
      {"sppt", "Rich model, projections and candidate results", "Metamorphic/certificate/guard observation model", "Pass/fail certificates, authority and diagnostics", "Stable IDs and declared observation maps", "Uses source result units without reinterpretation", "A certificate is valid only for its declared observables/model scope"},
      {"time_series", "Rich model, profiles, scenarios and prior state", "UC to OPF to PF plus SOC/lifecycle state", "Time-indexed dispatch/PF/state and per-step validity", "Stable component IDs; time index explicit", "MW/MWh, hours, currency and emissions", "Dispatch replay must not mutate authored control semantics"},
      {"validation", "Rich authored model", "Four-level structural/electrical/solver-ready checks", "ValidationReport with stable component references", "Stable IDs and domain-qualified terminals", "Checks field-native units", "Validation reports defects; it does not silently repair model semantics"},
  };
  return rows;
}

}  // namespace

const std::vector<ComponentRuntimeSemantics>& component_runtime_semantics() {
  return components();
}

const std::vector<ModuleDataContract>& module_data_contracts() {
  return modules();
}

const ComponentRuntimeSemantics* find_component_runtime_semantics(
    std::string_view collection_path) {
  const auto& rows = components();
  const auto it = std::find_if(rows.begin(), rows.end(), [&](const auto& row) {
    return row.collection_path == collection_path;
  });
  return it == rows.end() ? nullptr : &*it;
}

const ModuleDataContract* find_module_data_contract(
    std::string_view source_module) {
  const auto& rows = modules();
  const auto it = std::find_if(rows.begin(), rows.end(), [&](const auto& row) {
    return row.source_module == source_module;
  });
  return it == rows.end() ? nullptr : &*it;
}

std::string to_string(RuntimeFidelity fidelity) {
  switch (fidelity) {
    case F::Exact: return "exact";
    case F::Equivalent: return "equivalent";
    case F::Aggregated: return "aggregated";
    case F::BoundaryInjection: return "boundary-injection";
    case F::Projected: return "projected";
    case F::Unsupported: return "unsupported";
    case F::NotApplicable: return "not-applicable";
  }
  return "unsupported";
}

}  // namespace hacdcpf::model
