# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.12 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.12")
   message(FATAL_ERROR "CMake >= 2.8.12 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.12...4.2)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS mipsolvers::mipsolvers mipsolvers::cholmod_vendored mipsolvers::umfpack_vendored mipsolvers::klu_vendored mipsolvers::fmt mipsolvers::highs)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target mipsolvers::mipsolvers
add_library(mipsolvers::mipsolvers STATIC IMPORTED)

set_target_properties(mipsolvers::mipsolvers PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "EIGEN_MAX_ALIGN_BYTES=32;NOMINMAX;WIN32_LEAN_AND_MEAN;MIPSOLVERS_HAVE_HFACTOR=1;HACDCPF_HAVE_HFACTOR=1;MIPSOLVERS_HAVE_HIGHS_LIB=1;HACDCPF_HAVE_HIGHS_LIB=1;MIPSOLVERS_NATIVE_BC_STRICT_HIGHS=1;MIPSOLVERS_NATIVE_BC_DYNAMIC_CUTS=1;MIPSOLVERS_HAVE_SUITESPARSE=1;HACDCPF_HAVE_SUITESPARSE=1;MIPSOLVERS_HAVE_UMFPACK=1;HACDCPF_HAVE_UMFPACK=1;MIPSOLVERS_HAVE_KLU=1;HACDCPF_HAVE_KLU=1;MIPSOLVERS_HAVE_CHOLMOD=1;HACDCPF_HAVE_CHOLMOD=1;MIPSOLVERS_HAVE_MKL_PARDISO=1;HACDCPF_HAVE_MKL_PARDISO=1;MIPSOLVERS_HAVE_PAPILO=1;HACDCPF_HAVE_PAPILO=1"
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Eigen3::Eigen;mipsolvers::fmt;nlohmann_json::nlohmann_json;\$<LINK_ONLY:mipsolvers::highs>;\$<LINK_ONLY:mipsolvers::umfpack_vendored>;\$<LINK_ONLY:mipsolvers::klu_vendored>;\$<LINK_ONLY:mipsolvers::cholmod_vendored>;\$<LINK_ONLY:>;\$<LINK_ONLY:>;\$<LINK_ONLY:>;\$<\$<PLATFORM_ID:Darwin>:-framework Accelerate>"
  INTERFACE_LINK_OPTIONS "/STACK:8388608"
)

# Create imported target mipsolvers::cholmod_vendored
add_library(mipsolvers::cholmod_vendored STATIC IMPORTED)

set_target_properties(mipsolvers::cholmod_vendored PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:>;\$<LINK_ONLY:>;\$<LINK_ONLY:>"
)

# Create imported target mipsolvers::umfpack_vendored
add_library(mipsolvers::umfpack_vendored STATIC IMPORTED)

set_target_properties(mipsolvers::umfpack_vendored PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:mipsolvers::cholmod_vendored>"
)

# Create imported target mipsolvers::klu_vendored
add_library(mipsolvers::klu_vendored STATIC IMPORTED)

set_target_properties(mipsolvers::klu_vendored PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:mipsolvers::cholmod_vendored>"
)

# Create imported target mipsolvers::fmt
add_library(mipsolvers::fmt STATIC IMPORTED)

set_target_properties(mipsolvers::fmt PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_COMPILE_OPTIONS "\$<\$<AND:\$<COMPILE_LANGUAGE:CXX>,\$<CXX_COMPILER_ID:MSVC>>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target mipsolvers::highs
add_library(mipsolvers::highs STATIC IMPORTED)

set_target_properties(mipsolvers::highs PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Threads::Threads>"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/mipsolversTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
