/// @file parallel_search.hpp
/// @brief Parallel branch-and-cut search driver.
///
/// ParallelSearchDriver wraps the heterogeneous multi-thread explorer/cut-worker
/// architecture into a clean component interface, driven by BCSolveContext instead
/// of the 20+ parameter signature used by the underlying explorer_thread.
///
/// Thread layout (all roles run concurrently):
///   - (n_threads - 1) Explorer threads: Diver, Prover, IPMDiver roles
///   - 1 Cut-worker thread: async GMI generation from submitted LP results
///
/// Synchronization is entirely through BCSolveContext shared state (pools,
/// incumbent, bounds, termination flag). Workers communicate only via the
/// shared pools and the context's atomic counters.

#pragma once

#include <atomic>
#include <cstdint>
#include <memory>
#include <string>
#include <thread>
#include <vector>

#include "hacdcpf/engine/detail/bc_fallback.hpp"
#include "hacdcpf/engine/detail/bc_threading.hpp"
#include "hacdcpf/engine/detail/bc_types.hpp"

namespace hacdcpf::engine::solver::native::milp::bc {

class BCSolveContext;

/// @struct ParallelSearchStats
/// @brief Statistics from parallel tree search.
struct ParallelSearchStats {
  int nodes_explored{0};       ///< Total nodes across all explorer threads.
  int nodes_pruned{0};         ///< Nodes pruned by incumbent or infeasibility.
  int solutions_found{0};      ///< Incumbent improvements during tree search.
  int work_steals{0};          ///< Work-stealing events between explorer threads.
  int cut_worker_cuts{0};      ///< Cuts generated by the dedicated cut worker.
  double search_time_sec{0.0}; ///< Wall-clock time in tree search.
  std::string termination_reason;
};

/// @struct ParallelWorkerConfig
/// @brief Per-worker thread configuration for parallel B&C.
struct ParallelWorkerConfig {
  /// Number of explorer threads (1 = effectively sequential parallel shell).
  int n_explorers{1};

  /// Whether to spawn a dedicated cut-worker thread for async GMI generation.
  bool use_cut_worker{false};

  /// Whether to enable work-stealing between explorer threads.
  bool enable_work_stealing{true};

  /// Deterministic execution: serialize node pops across threads via a token.
  bool deterministic_mode{false};

  /// Random seed for work-stealing victim selection (0 = non-deterministic).
  std::uint64_t random_seed{0x9E3779B97F4A7C15ULL};
};

/// @class ParallelSearchDriver
/// @brief Executes multi-thread branch-and-cut tree search.
///
/// Usage:
/// @code
///   BCSolveContext ctx(prob, opt);
///   RootSolvePhase root(ctx);
///   auto root_result = root.solve();
///
///   // Seed context with root incumbent/cuts/basis before launching parallel search.
///   ctx.cut_pool().seed(root_result.root_node.x_relax, ...);
///
///   ParallelSearchDriver parallel(ctx);
///   auto stats = parallel.execute(root_result.root_node);
/// @endcode
///
/// Thread safety:
/// - All shared state is in BCSolveContext (mutex/atomic protected).
/// - Each explorer has a private StandardFormLP copy (no basis sharing).
/// - Incumbent updates use CAS loop in ctx.update_incumbent().
class ParallelSearchDriver {
 public:
  /// Construct parallel search driver.
  /// @param context Shared B&C state (pools, bounds, pseudocosts, options).
  explicit ParallelSearchDriver(BCSolveContext& context);

  /// Execute parallel branch-and-cut tree search.
  /// @param root_node  Root node from root solve phase.
  /// @param config     Worker configuration (thread count, work-stealing, etc.).
  /// @return Search statistics (nodes, cuts, time, termination reason).
  ParallelSearchStats execute(
      const detail::Node& root_node,
      const ParallelWorkerConfig& config = {});

 private:
  /// Launch all explorer and cut-worker threads.
  /// @param root_node   Root node to seed shared queue with.
  /// @param config      Worker configuration.
  void launch_workers(
      const detail::Node& root_node,
      const ParallelWorkerConfig& config);

  /// Join all workers and collect final statistics.
  ParallelSearchStats join_workers();

  /// Determine thread roles from options and worker count.
  /// @param n_explorers  Number of explorer threads.
  /// @return Vector of WorkerRole per explorer thread.
  std::vector<detail::WorkerRole> assign_roles(int n_explorers) const;

  // ─────────────────────────────────────────────────────────────────────
  // Owned state (lifetime = one execute() call)
  // ─────────────────────────────────────────────────────────────────────

  BCSolveContext& ctx_;

  // Shared infrastructure for the parallel tree.
  std::unique_ptr<detail::WorkStealingPool> steal_pool_;

  // Threads (populated during launch_workers, joined in join_workers).
  std::vector<std::thread> explorer_threads_;
  std::thread cut_worker_thread_;
  bool has_cut_worker_{false};

  // Parallel termination flag (separate from ctx_ terminate_flag to allow
  // a clean 2-phase shutdown: signal → drain queues → join).
  std::atomic<bool> should_stop_{false};
  std::atomic<int> active_explorers_{0};

  // Cross-thread shared pools (owned here, separate from ctx_ pools which
  // are the canonical source of truth; bridge is synced in execute()).
  // SharedIncumbent bridges ctx_.update_incumbent() with the thread API.
  detail::SharedIncumbent shared_inc_;
  detail::AtomicBCStats atomic_stats_;
  detail::ActiveNodeBounds active_bounds_;
  // FallbackLogger must outlive explorer threads; created per execute() call.
  std::unique_ptr<detail::FallbackLogger> fallback_logger_;

  // Cross-thread shared queues (initialized in launch_workers).
  std::unique_ptr<detail::ThreadSafeNodeQueue> node_queue_;
  std::unique_ptr<detail::CutRequestQueue> cut_req_queue_;
  std::unique_ptr<detail::SharedImplicationGraph> shared_impl_graph_;
  std::unique_ptr<detail::DeterministicTurnToken> det_token_;
};

}  // namespace hacdcpf::engine::solver::native::milp::bc
