/// sppt/certificate.cpp
/// ====================
/// MR3 semantic-preservation certificate corpus (Thm. 5.6, Pillar 3).

#include "hacdcpf/sppt/certificate.hpp"

#include <iomanip>
#include <sstream>
#include <stdexcept>
#include <string>

#include "hacdcpf/io/json_io.hpp"
#include "hacdcpf/io/matpower_parser.hpp"
#include "hacdcpf/projection/project_to_canonical.hpp"
#include "hacdcpf/sppt/metamorphic.hpp"

namespace hacdcpf::sppt {
namespace {

std::string sci(double v) {
  std::ostringstream os;
  os << std::scientific << std::setprecision(2) << v;
  return os.str();
}

std::string latex_escape(const std::string& s) {
  std::string out;
  out.reserve(s.size() + 8);
  for (char c : s) {
    if (c == '_' || c == '%' || c == '#' || c == '&') out.push_back('\\');
    out.push_back(c);
  }
  return out;
}

const char* mark(bool ok) { return ok ? "\\checkmark" : "$\\times$"; }

}  // namespace

// ── Certificate renderers ────────────────────────────────────────────────────
bool Certificate::all_pass() const {
  for (const auto& r : rows) {
    if (!r.pf_pass) return false;
    if (r.opf_converged && !r.opf_pass) return false;
  }
  return true;
}

int Certificate::pass_count() const {
  int n = 0;
  for (const auto& r : rows)
    if (r.pf_pass && (r.opf_pass || !r.opf_converged)) ++n;
  return n;
}

std::string Certificate::to_csv() const {
  std::ostringstream os;
  os << "case,n_ac_bus,n_dc_bus,pf_converged,pf_residual,pf_pass,"
        "opf_converged,opf_dual_residual,opf_pass,tolerance,note\n";
  for (const auto& r : rows) {
    os << r.case_name << ',' << r.n_ac_bus << ',' << r.n_dc_bus << ','
       << (r.pf_converged ? 1 : 0) << ',' << sci(r.pf_residual) << ','
       << (r.pf_pass ? 1 : 0) << ',' << (r.opf_converged ? 1 : 0) << ','
       << sci(r.opf_dual_residual) << ',' << (r.opf_pass ? 1 : 0) << ','
       << sci(r.tolerance) << ',' << r.note << '\n';
  }
  return os.str();
}

std::string Certificate::to_latex() const {
  std::ostringstream os;
  os << "% Auto-generated by hacdcpf::sppt::Certificate::to_latex()\n"
     << "% MR3 semantic-preservation certificate (Thm. 5.6). Tolerance = "
     << sci(tolerance) << ".\n"
     << "\\begin{tabular}{@{}lrrrcrc@{}}\n"
     << "\\toprule\n"
     << "Case & $n_{\\mathrm{ac}}$ & $n_{\\mathrm{dc}}$ & "
        "$\\|\\Delta V\\|_\\infty$ & PF & $\\|\\Delta\\lambda\\|_\\infty$ & OPF \\\\\n"
     << "\\midrule\n";
  for (const auto& r : rows) {
    os << "\\texttt{" << latex_escape(r.case_name) << "} & " << r.n_ac_bus
       << " & " << r.n_dc_bus << " & " << sci(r.pf_residual) << " & "
       << mark(r.pf_pass) << " & "
       << (r.opf_converged ? sci(r.opf_dual_residual) : std::string("--"))
       << " & " << (r.opf_converged ? mark(r.opf_pass) : std::string("--"))
       << " \\\\\n";
  }
  os << "\\bottomrule\n\\end{tabular}\n";
  return os.str();
}

// ── Certification ────────────────────────────────────────────────────────────
CertificateRow certify_case(const HybridPowerSystem& sys, std::string case_name,
                            double tol) {
  CertificateRow row;
  row.case_name = std::move(case_name);
  row.tolerance = tol;
  row.n_ac_bus = n_ac_buses(sys);
  row.n_dc_bus = n_dc_buses(sys);

  const MetamorphicResult pf = mr3_semantic_preservation_pf(sys, tol);
  row.pf_residual = pf.residual;
  row.pf_pass = pf.passed;
  row.pf_converged = pf.detail.find("non-convergence") == std::string::npos;

  const MetamorphicResult du = mr3_semantic_preservation_opf_dual(sys, tol);
  row.opf_dual_residual = du.residual;
  row.opf_pass = du.passed;
  row.opf_converged = du.detail.find("non-convergence") == std::string::npos &&
                      du.detail.find("vacuous") == std::string::npos;
  return row;
}

Certificate certify_corpus(
    const std::vector<std::pair<std::string, std::string>>& cases, double tol) {
  Certificate cert;
  cert.tolerance = tol;
  for (const auto& [name, path] : cases) {
    try {
      HybridPowerSystem sys;
      if (path.size() >= 2 && path.substr(path.size() - 2) == ".m") {
        sys = io::parse_matpower(path);
      } else {
        sys = io::load_json(path);
      }
      cert.rows.push_back(certify_case(sys, name, tol));
    } catch (const std::exception& e) {
      CertificateRow row;
      row.case_name = name;
      row.tolerance = tol;
      row.note = std::string("load/solve failed: ") + e.what();
      cert.rows.push_back(row);
    }
  }
  return cert;
}

}  // namespace hacdcpf::sppt
