function make_terminal_state_boundary_figure()
% Diagnostic evidence for the terminal-state reliability-boundary pilot.
% Inputs are generated by tools/terminal_state_boundary_study.cpp.

paperDir = fileparts(mfilename('fullpath'));
tripTags = ["5ms", "2p5ms", "1p25ms", "0p625ms", "0p3125ms"];
dtMs = [5, 2.5, 1.25, 0.625, 0.3125];
pTrip = zeros(size(dtMs));
pMomentary = zeros(size(dtMs));
for k = 1:numel(tripTags)
    data = readResult(paperDir, "terminal_state_boundary_trip_results_" + ...
        tripTags(k) + ".json");
    pTrip(k) = data.summary.p_protective_trip_uniform_grid;
    pMomentary(k) = data.summary.p_momentary_cessation_uniform_grid;
end

reconnectTags = ["5ms", "2p5ms", "1p25ms", "0p625ms"];
reconnectDtMs = [5, 2.5, 1.25, 0.625];
tripTime = nan(size(reconnectDtMs));
reconnectTime = nan(size(reconnectDtMs));
fullPowerTime = nan(size(reconnectDtMs));
failureTime = nan(size(reconnectDtMs));
for k = 1:numel(reconnectTags)
    data = readResult(paperDir, "terminal_state_boundary_reconnect_smoke_" + ...
        reconnectTags(k) + ".json");
    rows = data.scenarios;
    selected = find(arrayfun(@(x) abs(x.fault_r_pu - 0.01) < 1e-12 && ...
        abs(x.clearing_duration_s - 0.30) < 1e-12, rows), 1);
    if isempty(selected)
        error('Deep-fault reconnect scenario is absent from %s.', reconnectTags(k));
    end
    row = rows(selected);
    tripTime(k) = nullableNumber(row.trip_time_s);
    reconnectTime(k) = nullableNumber(row.reconnect_time_s);
    fullPowerTime(k) = nullableNumber(row.full_power_time_s);
    token = regexp(row.message, 'failed at t=([0-9.]+)s', 'tokens', 'once');
    if ~isempty(token)
        failureTime(k) = str2double(token{1});
    end
end

coarse = readResult(paperDir, "terminal_state_boundary_reconnect_smoke_5ms.json");
boundary = coarse.static_model_boundary;
restorationDelay = arrayfun(@(x) x.network_restoration_delay_s, boundary);
relativeBias = 100 * arrayfun(@(x) nullableNumber(x.relative_static_underestimate), boundary);

blue = [0.08, 0.36, 0.64];
red = [0.72, 0.18, 0.16];
green = [0.12, 0.50, 0.31];
gold = [0.88, 0.58, 0.10];
gray = [0.38, 0.40, 0.43];

fig = figure('Color', 'w', 'Position', [80, 80, 1420, 430]);
layout = tiledlayout(fig, 1, 3, 'TileSpacing', 'compact', 'Padding', 'compact');

nexttile(layout, 1);
ax1 = gca;
semilogx(dtMs, 100 * pTrip, '-o', 'Color', blue, 'MarkerFaceColor', blue, ...
    'LineWidth', 1.6, 'MarkerSize', 6);
hold on;
semilogx(dtMs, 100 * pMomentary, '--s', 'Color', gold, ...
    'MarkerFaceColor', 'w', 'LineWidth', 1.4, 'MarkerSize', 6);
set(gca, 'XDir', 'reverse', 'XTick', fliplr(dtMs));
xlabel('DAE step size (ms)');
ylabel('Uniform-grid fraction (%)');
title('(a) Near-fault outcome convergence');
lg = legend({'Protective trip', 'Momentary-cessation diagnostic'}, ...
    'Location', 'southwest', 'Box', 'off');
lg.TextColor = [0.12, 0.13, 0.15];
lg.Color = 'w';
ylim([0, 58]);
grid on;
styleAxes(ax1);

nexttile(layout, 2);
ax2 = gca;
hold on;
for k = 1:numel(reconnectDtMs)
    y = numel(reconnectDtMs) - k + 1;
    if isfinite(failureTime(k))
        plot([0, failureTime(k)], [y, y], '-', 'Color', red, 'LineWidth', 1.8);
        plot(failureTime(k), y, 'x', 'Color', red, 'LineWidth', 2.0, 'MarkerSize', 8);
    else
        plot([0, 25], [y, y], '-', 'Color', gray, 'LineWidth', 1.0);
        if isfinite(tripTime(k))
            plot(tripTime(k), y, 'v', 'Color', red, 'MarkerFaceColor', red, ...
                'MarkerSize', 6);
        end
        if isfinite(reconnectTime(k))
            plot(reconnectTime(k), y, 'o', 'Color', blue, 'MarkerFaceColor', blue, ...
                'MarkerSize', 6);
        else
            plot(25, y, '>', 'Color', gray, 'MarkerFaceColor', 'w', 'MarkerSize', 6);
        end
        if isfinite(fullPowerTime(k))
            plot(fullPowerTime(k), y, 's', 'Color', green, 'MarkerFaceColor', green, ...
                'MarkerSize', 6);
        end
    end
end
hTrip = plot(nan, nan, 'v', 'Color', red, 'MarkerFaceColor', red, 'MarkerSize', 6);
hReconnect = plot(nan, nan, 'o', 'Color', blue, 'MarkerFaceColor', blue, 'MarkerSize', 6);
hFull = plot(nan, nan, 's', 'Color', green, 'MarkerFaceColor', green, 'MarkerSize', 6);
hCensored = plot(nan, nan, '>', 'Color', gray, 'MarkerFaceColor', 'w', 'MarkerSize', 6);
hFailure = plot(nan, nan, 'x', 'Color', red, 'LineWidth', 2.0, 'MarkerSize', 7);
xline(25, ':', 'Color', gray, 'LineWidth', 1.0);
yticks(1:4);
yticklabels({'0.625', '1.25', '2.5', '5'});
xlabel('Event time (s)');
ylabel('DAE step size (ms)');
title('(b) Reconnect time is not step-converged');
xlim([0, 26]);
ylim([0.5, 4.5]);
grid on;
styleAxes(ax2);
lg2 = legend([hTrip, hReconnect, hFull, hCensored, hFailure], ...
    {'Trip', 'Reconnect', 'Full power', 'No reconnect', 'DAE failure'}, ...
    'Location', 'northwest', 'NumColumns', 2, 'Box', 'off');
lg2.TextColor = [0.12, 0.13, 0.15];
lg2.Color = 'w';
lg2.FontSize = 8;

nexttile(layout, 3);
ax3 = gca;
semilogx(restorationDelay, relativeBias, '--o', 'Color', red, ...
    'MarkerFaceColor', 'w', 'LineWidth', 1.5, 'MarkerSize', 6);
hold on;
yline(5, ':', '5% adequacy gate', 'Color', green, 'LineWidth', 1.3, ...
    'LabelHorizontalAlignment', 'left');
xlabel('Network restoration delay (s)');
ylabel('Static EENS underestimate (%)');
title('(c) Coarse-step candidate, rejected');
xticks(restorationDelay);
ylim([-2, max(relativeBias) + 8]);
grid on;
text(1.15, max(relativeBias) + 2, 'Not admissible: long-horizon step test failed', ...
    'Color', red, 'FontSize', 9, 'VerticalAlignment', 'top');
styleAxes(ax3);

set(findall(fig, '-property', 'FontName'), 'FontName', 'Helvetica');
set(findall(fig, '-property', 'FontSize'), 'FontSize', 10);
exportgraphics(fig, fullfile(paperDir, 'terminal_state_boundary_diagnostic.pdf'), ...
    'ContentType', 'vector');
exportgraphics(fig, fullfile(paperDir, 'terminal_state_boundary_diagnostic.png'), ...
    'Resolution', 240);
close(fig);

fineTags = ["0p625ms", "0p3125ms"];
fineLabels = {'0.625 ms transient-aware', '0.3125 ms transient-aware'};
finiteDelay = [];
staticEnsWh = [];
transientEnsWh = zeros(2, 5);
finiteBiasPct = zeros(2, 5);
for k = 1:numel(fineTags)
    fineData = readResult(paperDir, "terminal_state_boundary_trip_results_" + ...
        fineTags(k) + ".json");
    comparison = fineData.finite_horizon_static_transient_comparison;
    if isempty(finiteDelay)
        finiteDelay = arrayfun(@(x) x.network_restoration_delay_s, comparison);
        staticEnsWh = 1e6 * arrayfun(@(x) x.mean_static_ens_mwh_per_event, comparison);
    end
    transientEnsWh(k, :) = 1e6 * ...
        arrayfun(@(x) x.mean_transient_ens_mwh_per_event, comparison);
    finiteBiasPct(k, :) = 100 * ...
        arrayfun(@(x) x.relative_static_underestimate, comparison);
end

fig2 = figure('Color', 'w', 'Position', [100, 100, 1040, 410]);
layout2 = tiledlayout(fig2, 1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');

nexttile(layout2, 1);
ax4 = gca;
plot(finiteDelay, staticEnsWh, '-o', 'Color', gray, ...
    'MarkerFaceColor', gray, 'LineWidth', 1.6, 'MarkerSize', 6);
hold on;
plot(finiteDelay, transientEnsWh(1, :), '--s', 'Color', gold, ...
    'MarkerFaceColor', 'w', 'LineWidth', 1.5, 'MarkerSize', 6);
plot(finiteDelay, transientEnsWh(2, :), '-d', 'Color', blue, ...
    'MarkerFaceColor', blue, 'LineWidth', 1.5, 'MarkerSize', 6);
xlabel('Network restoration delay (s)');
ylabel('Mean ENS per event (Wh)');
title('(a) Static model is the nested baseline');
xticks(finiteDelay);
grid on;
styleAxes(ax4);
lg3 = legend([{'Static'}, fineLabels], 'Location', 'northwest', 'Box', 'off');
lg3.TextColor = [0.12, 0.13, 0.15];
lg3.Color = 'w';
lg3.FontSize = 8;

nexttile(layout2, 2);
ax5 = gca;
plot(finiteDelay, finiteBiasPct(1, :), '--s', 'Color', gold, ...
    'MarkerFaceColor', 'w', 'LineWidth', 1.5, 'MarkerSize', 6);
hold on;
plot(finiteDelay, finiteBiasPct(2, :), '-d', 'Color', blue, ...
    'MarkerFaceColor', blue, 'LineWidth', 1.5, 'MarkerSize', 6);
yline(5, ':', '5% adequacy gate', 'Color', green, 'LineWidth', 1.3, ...
    'LabelHorizontalAlignment', 'right');
xlabel('Network restoration delay (s)');
ylabel('Static ENS underestimate (%)');
title('(b) Admitted 3 s applicability boundary');
xticks(finiteDelay);
ylim([-2, 50]);
grid on;
styleAxes(ax5);
lg4 = legend(fineLabels, 'Location', 'northeast', 'Box', 'off');
lg4.TextColor = [0.12, 0.13, 0.15];
lg4.Color = 'w';
lg4.FontSize = 8;

set(findall(fig2, '-property', 'FontName'), 'FontName', 'Helvetica');
set(findall(fig2, '-property', 'FontSize'), 'FontSize', 10);
exportgraphics(fig2, fullfile(paperDir, ...
    'static_transient_finite_horizon_comparison.pdf'), 'ContentType', 'vector');
exportgraphics(fig2, fullfile(paperDir, ...
    'static_transient_finite_horizon_comparison.png'), 'Resolution', 240);
close(fig2);
end

function styleAxes(ax)
ax.Color = 'w';
ax.XColor = [0.12, 0.13, 0.15];
ax.YColor = [0.12, 0.13, 0.15];
ax.GridColor = [0.68, 0.70, 0.72];
ax.MinorGridColor = [0.82, 0.83, 0.84];
ax.GridAlpha = 0.35;
ax.MinorGridAlpha = 0.18;
ax.Title.Color = [0.08, 0.09, 0.10];
ax.XLabel.Color = [0.12, 0.13, 0.15];
ax.YLabel.Color = [0.12, 0.13, 0.15];
box(ax, 'on');
try
    axtoolbar(ax, 'Visible', 'off');
catch
end
end

function data = readResult(paperDir, name)
path = fullfile(paperDir, name);
if ~isfile(path)
    error('Required simulation result is absent: %s', path);
end
data = jsondecode(fileread(path));
end

function value = nullableNumber(raw)
if isempty(raw)
    value = nan;
else
    value = double(raw);
end
end
