# HiGHS 1.15.1 source list (reconstructed from build artifacts)

set(highs_sources
  ${CMAKE_CURRENT_LIST_DIR}/HighsExternalApi.cpp
  ${CMAKE_CURRENT_LIST_DIR}/HighsExternalDeps.cpp
  ${CMAKE_CURRENT_LIST_DIR}/extern/HighsExtrasApi.cpp
  ${CMAKE_CURRENT_LIST_DIR}/extern/HighsExtrasExternalDeps.cpp
  ${CMAKE_CURRENT_LIST_DIR}/interfaces/highs_c_api.cpp
  ${CMAKE_CURRENT_LIST_DIR}/io/Filereader.cpp
  ${CMAKE_CURRENT_LIST_DIR}/io/FilereaderLp.cpp
  ${CMAKE_CURRENT_LIST_DIR}/io/FilereaderMps.cpp
  ${CMAKE_CURRENT_LIST_DIR}/io/HMPSIO.cpp
  ${CMAKE_CURRENT_LIST_DIR}/io/HMpsFF.cpp
  ${CMAKE_CURRENT_LIST_DIR}/io/HighsIO.cpp
  ${CMAKE_CURRENT_LIST_DIR}/io/LoadOptions.cpp
  ${CMAKE_CURRENT_LIST_DIR}/io/filereaderlp/reader.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/IpxWrapper.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/Highs.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsCallback.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsDebug.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsDeprecated.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsIis.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsInfo.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsInfoDebug.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsInterface.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsLp.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsLpUtils.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsModelUtils.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsOptions.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsRanging.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsRunData.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsSolution.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsSolutionDebug.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsSolve.cpp
  ${CMAKE_CURRENT_LIST_DIR}/lp_data/HighsStatus.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsCliqueTable.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsConflictPool.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsCutGeneration.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsCutPool.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsDebugSol.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsDomain.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsDynamicRowMatrix.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsFeasibilityJump.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsGFkSolve.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsImplications.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsLpAggregator.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsLpRelaxation.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsMipSolver.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsMipSolverData.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsMipWorker.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsModkSeparator.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsNodeQueue.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsObjectiveFunction.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsPathSeparator.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsPrimalHeuristics.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsPseudocost.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsRedcostFixing.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsSearch.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsSeparation.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsSeparator.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsTableauSeparator.cpp
  ${CMAKE_CURRENT_LIST_DIR}/mip/HighsTransformedLp.cpp
  ${CMAKE_CURRENT_LIST_DIR}/model/HighsHessian.cpp
  ${CMAKE_CURRENT_LIST_DIR}/model/HighsHessianUtils.cpp
  ${CMAKE_CURRENT_LIST_DIR}/model/HighsModel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/parallel/HighsTaskExecutor.cpp
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/CupdlpWrapper.cpp
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/HiPdlpWrapper.cpp
  ${CMAKE_CURRENT_LIST_DIR}/presolve/HPresolve.cpp
  ${CMAKE_CURRENT_LIST_DIR}/presolve/HPresolveAnalysis.cpp
  ${CMAKE_CURRENT_LIST_DIR}/presolve/HPresolveTest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/presolve/HighsPostsolveStack.cpp
  ${CMAKE_CURRENT_LIST_DIR}/presolve/HighsSymmetry.cpp
  ${CMAKE_CURRENT_LIST_DIR}/presolve/ICrash.cpp
  ${CMAKE_CURRENT_LIST_DIR}/presolve/ICrashUtil.cpp
  ${CMAKE_CURRENT_LIST_DIR}/presolve/ICrashX.cpp
  ${CMAKE_CURRENT_LIST_DIR}/presolve/PresolveComponent.cpp
  ${CMAKE_CURRENT_LIST_DIR}/qpsolver/a_asm.cpp
  ${CMAKE_CURRENT_LIST_DIR}/qpsolver/a_quass.cpp
  ${CMAKE_CURRENT_LIST_DIR}/qpsolver/basis.cpp
  ${CMAKE_CURRENT_LIST_DIR}/qpsolver/perturbation.cpp
  ${CMAKE_CURRENT_LIST_DIR}/qpsolver/quass.cpp
  ${CMAKE_CURRENT_LIST_DIR}/qpsolver/ratiotest.cpp
  ${CMAKE_CURRENT_LIST_DIR}/qpsolver/scaling.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HEkk.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HEkkControl.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HEkkDebug.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HEkkDual.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HEkkDualMulti.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HEkkDualRHS.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HEkkDualRow.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HEkkInterface.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HEkkPrimal.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HSimplex.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HSimplexDebug.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HSimplexNla.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HSimplexNlaDebug.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HSimplexNlaFreeze.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HSimplexNlaProductForm.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HSimplexReport.cpp
  ${CMAKE_CURRENT_LIST_DIR}/simplex/HighsSimplexAnalysis.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test_kkt/DevKkt.cpp
  ${CMAKE_CURRENT_LIST_DIR}/test_kkt/KktCh2.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HighsDynamicLibrary.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HFactor.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HFactorDebug.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HFactorExtend.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HFactorRefactor.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HFactorUtils.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HSet.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HVectorBase.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HighsHash.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HighsLinearSumBounds.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HighsMatrixPic.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HighsMatrixUtils.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HighsSort.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HighsSparseMatrix.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/HighsUtils.cpp
  ${CMAKE_CURRENT_LIST_DIR}/util/stringutil.cpp
)

set(cupdlp_sources
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/CupdlpWrapper.cpp
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/HiPdlpWrapper.cpp
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/hipdlp/linalg.cc
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/hipdlp/logger.cc
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/hipdlp/pdhg.cc
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/hipdlp/restart.cc
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/hipdlp/scaling.cc
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/cupdlp/cupdlp_cs.c
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/cupdlp/cupdlp_linalg.c
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/cupdlp/cupdlp_proj.c
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/cupdlp/cupdlp_restart.c
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/cupdlp/cupdlp_scaling.c
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/cupdlp/cupdlp_solver.c
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/cupdlp/cupdlp_step.c
  ${CMAKE_CURRENT_LIST_DIR}/pdlp/cupdlp/cupdlp_utils.c
)

set(ipx_sources
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/basiclu_kernel.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/basiclu_wrapper.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/basis.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/conjugate_residuals.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/control.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/crossover.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/diagonal_precond.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/forrest_tomlin.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/guess_basis.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/indexed_vector.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/info.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/ipm.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/ipx_c.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/iterate.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/kkt_solver.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/kkt_solver_basis.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/kkt_solver_diag.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/linear_operator.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/lp_solver.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/lu_factorization.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/lu_update.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/maxvolume.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/model.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/normal_matrix.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/sparse_matrix.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/sparse_utils.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/splitted_normal_matrix.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/starting_basis.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/symbolic_invert.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/timer.cc
  ${CMAKE_CURRENT_LIST_DIR}/ipm/ipx/utils.cc
)

set(basiclu_sources
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/basiclu_factorize.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/basiclu_get_factors.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/basiclu_initialize.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/basiclu_object.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/basiclu_solve_dense.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/basiclu_solve_for_update.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/basiclu_solve_sparse.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/basiclu_update.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_build_factors.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_condest.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_dfs.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_factorize_bump.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_file.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_garbage_perm.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_initialize.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_internal.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_markowitz.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_matrix_norm.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_pivot.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_residual_test.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_setup_bump.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_singletons.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_solve_dense.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_solve_for_update.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_solve_sparse.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_solve_symbolic.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_solve_triangular.c
  ${CMAKE_CURRENT_LIST_DIR}/ipm/basiclu/lu_update.c
)

set(highs_headers)
set(cupdlp_headers)
set(ipx_headers)
set(basiclu_headers)
set(hipo_sources
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/ipm/IpmData.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/ipm/FactorHiGHSSolver.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/ipm/Control.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/ipm/Iterate.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/ipm/KktMatrix.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/ipm/Model.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/ipm/PreProcess.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/ipm/Refine.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/ipm/Solver.cpp
)

set(factor_highs_sources
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/Analyse.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/CallAndTimeBlas.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/CliqueStack.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/DataCollector.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/DenseFactHybrid.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/DenseFactKernel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/DgemmParallel.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/FactorHiGHS.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/Factorise.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/FormatHandler.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/HybridHybridFormatHandler.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/HybridSolveHandler.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/KrylovMethodsIpm.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/Numeric.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/SolveHandler.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/Swaps.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/factorhighs/Symbolic.cpp
)

set(hipo_util_sources
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/auxiliary/Auxiliary.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/auxiliary/KrylovMethods.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/auxiliary/Logger.cpp
  ${CMAKE_CURRENT_LIST_DIR}/ipm/hipo/auxiliary/VectorOperations.cpp
)
