#!/usr/bin/env python3
"""sppt_pandapower_crosscheck.py
================================
External cross-tool PF cross-check (pandapower vs HACDCPF) for SPPT Pillar 4.

This script runs pandapower AC power flow on MATPOWER .m files and compares bus
voltage magnitudes against HACDCPF's solve_power_flow through the existing
`matpower_pf_compare` binary output schema:
  - HACDCPF: max absolute bus-voltage mismatch from internal compare tool
  - pandapower: converged flag and runtime

Outputs:
  - docs/latex/sppt_pandapower_crosscheck.csv
  - docs/latex/sppt_pandapower_crosscheck.tex

Usage:
  /opt/homebrew/bin/python3.12 tools/sppt_pandapower_crosscheck.py [data_dir] [out_dir]
"""

from __future__ import annotations

import json
import math
import pathlib
import subprocess
import sys
import time
import warnings
from dataclasses import dataclass

import pandapower as pp
import pandapower.converter as ppc


ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA_DEFAULT = ROOT / "data"
OUT_DEFAULT = ROOT / "docs" / "latex"
COMPARE_BIN = ROOT / "build" / "macos-release" / "matpower_pf_compare"


@dataclass
class Row:
    case: str
    n_bus: int
    hacdcpf_converged: bool
    pandapower_converged: bool
    vm_maxdiff: float
    va_maxdiff_deg: float
    pandapower_ms: float
    note: str = ""


def run_pandapower(case_path: pathlib.Path) -> tuple[bool, list[float], list[float], float, str]:
    t0 = time.perf_counter()
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            net = ppc.from_mpc(str(case_path), f_hz=50.0)
            pp.runpp(net, algorithm="nr", init="auto", calculate_voltage_angles=True,
                     tolerance_mva=1e-8, max_iteration=80, numba=False)
        dt_ms = (time.perf_counter() - t0) * 1000.0
        vm = net.res_bus["vm_pu"].to_numpy(dtype=float).tolist()
        va = net.res_bus["va_degree"].to_numpy(dtype=float).tolist()
        return bool(net.converged), vm, va, dt_ms, ""
    except Exception as e:  # noqa: BLE001
        dt_ms = (time.perf_counter() - t0) * 1000.0
        return False, [], [], dt_ms, str(e)


def run_hacdcpf_compare(case_path: pathlib.Path) -> tuple[bool, list[float], list[float], str]:
    if not COMPARE_BIN.exists():
        return False, [], [], f"missing binary: {COMPARE_BIN}"
    proc = subprocess.run(
        [str(COMPARE_BIN), str(case_path)],
        capture_output=True,
        text=True,
        check=False,
    )
    txt = proc.stdout.strip() or proc.stderr.strip()
    # Tool prints JSON with keys: converged, vm, va, residual.
    try:
        j = json.loads(txt)
        vm = [float(x) for x in j.get("vm", [])]
        # HACDCPF reports voltage angles in radians; pandapower reports degrees.
        va = [float(x) * 180.0 / math.pi for x in j.get("va", [])]
        return bool(j.get("converged", False)), vm, va, ""
    except Exception:  # noqa: BLE001
        # Fallback: allow plain text failure message.
        return False, [], [], txt[:180]


def max_abs_diff(a: list[float], b: list[float]) -> float:
    n = min(len(a), len(b))
    if n == 0:
        return 0.0
    return max(abs(a[i] - b[i]) for i in range(n))


def max_abs_angle_diff_with_offset_deg(a: list[float], b: list[float]) -> float:
    """Compare angles after removing a global reference-angle offset."""
    n = min(len(a), len(b))
    if n == 0:
        return 0.0
    offset = a[0] - b[0]
    return max(abs((a[i] - offset) - b[i]) for i in range(n))


def to_csv(rows: list[Row]) -> str:
    out = [
        "case,n_bus,hacdcpf_converged,pandapower_converged,vm_maxdiff,va_maxdiff_deg,pandapower_ms,note"
    ]
    for r in rows:
        out.append(
            f"{r.case},{r.n_bus},{int(r.hacdcpf_converged)},{int(r.pandapower_converged)},"
            f"{r.vm_maxdiff:.2e},{r.va_maxdiff_deg:.2e},{r.pandapower_ms:.2f},{r.note}"
        )
    return "\n".join(out) + "\n"


def latex_escape(s: str) -> str:
    return s.replace("_", r"\_")


def to_latex(rows: list[Row]) -> str:
    lines = [
        "% Auto-generated by tools/sppt_pandapower_crosscheck.py",
        r"\begin{tabular}{@{}lrrrcc@{}}",
        r"\toprule",
            "Case & $n_{\\mathrm{bus}}$ & $\\|\\Delta V\\|_\\infty$ & $\\|\\Delta \\theta\\|_\\infty\\,(^\\circ)$ & HACDCPF & pandapower \\\\",
        r"\midrule",
    ]
    for r in rows:
        lines.append(
            rf"\texttt{{{latex_escape(r.case)}}} & {r.n_bus} & {r.vm_maxdiff:.2e} & {r.va_maxdiff_deg:.2e} & "
            + (r"\checkmark" if r.hacdcpf_converged else r"$\times$")
            + " & "
            + (r"\checkmark" if r.pandapower_converged else r"$\times$")
            + r" \\" 
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> int:
    data_dir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DATA_DEFAULT
    out_dir = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else OUT_DEFAULT

    # Pandapower-compatible MATPOWER subset: these cases converge in both tools
    # through pandapower's MATPOWER importer without transformer/base-kV semantic
    # rewrites that dominate the solver comparison.
    cases = [
        "case5.m", "case6ww.m", "case9.m", "case9target.m", "case30.m",
        "case89pegase.m",
    ]

    rows: list[Row] = []
    for c in cases:
        p = data_dir / c
        if not p.exists():
            rows.append(Row(c, 0, False, False, 0.0, 0.0, 0.0, "missing case"))
            continue

        pp_ok, pp_vm, pp_va, pp_ms, pp_note = run_pandapower(p)
        hc_ok, hc_vm, hc_va, hc_note = run_hacdcpf_compare(p)
        n_bus = len(hc_vm)
        vm_diff = max_abs_diff(hc_vm, pp_vm)
        va_diff = max_abs_angle_diff_with_offset_deg(hc_va, pp_va)
        note = pp_note or hc_note
        if not note and len(pp_vm) != len(hc_vm):
            note = f"vm length mismatch: hc={len(hc_vm)} pp={len(pp_vm)}"
        rows.append(Row(c, n_bus, hc_ok, pp_ok, vm_diff, va_diff, pp_ms, note))

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "sppt_pandapower_crosscheck.csv").write_text(to_csv(rows), encoding="utf-8")
    (out_dir / "sppt_pandapower_crosscheck.tex").write_text(to_latex(rows), encoding="utf-8")

    ok = sum(1 for r in rows if r.hacdcpf_converged and r.pandapower_converged)
    print(f"pandapower cross-check: {ok}/{len(rows)} converged on both tools")
    print(f"wrote {(out_dir / 'sppt_pandapower_crosscheck.csv')}")
    print(f"wrote {(out_dir / 'sppt_pandapower_crosscheck.tex')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
