#!/usr/bin/env python3
"""Multi-resolution IEEE RTS-24 / IEEE-118 week-ahead risk benchmark.

This is a research prototype, not a production market-clearing implementation.
It preserves the information structure proposed in the accompanying technical
document while keeping the stochastic recourse problems linear:

* D+1: 96 x 15-minute periods;
* D+2--D+3: 48 x hourly periods;
* D+4--D+7: 12 x peak/flat/valley eight-hour blocks;
* RTS-24: detailed local DC network for D+1--D+3;
* IEEE-118: a hidden benchmark environment that synthesizes observable market
  outcomes; the Yunnan optimizer never receives external buses, branches,
  generators, loads, bids, or dispatch decisions;
* local SCUC and hydro vibration-zone results are represented by fixed market
  templates, so each conditional operating-scenario recourse is an LP.

The IEEE-118 data are read from this repository's production case builder.  The
RTS-24 skeleton follows the public IEEE RTS / MATPOWER 24-bus topology; resource
classification and all Yunnan-oriented additions are synthetic and explicitly
identified below.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Sequence, Tuple

import numpy as np
from scipy.optimize import linprog
from scipy.sparse import coo_matrix


ROOT = Path(__file__).resolve().parents[2]
RESULTS_PATH = ROOT / "docs" / "yunnan_ieee24_118_results.json"
EENS_CVAR90_LIMIT_GWH = 0.05
CURTAILMENT_CVAR90_LIMIT_GWH = 1.50
EXPECTED_RESERVE_SHORTFALL_LIMIT_GWH = 0.01


@dataclass(frozen=True)
class Branch:
    f: int
    t: int
    x: float
    rating: float


@dataclass(frozen=True)
class Generator:
    name: str
    bus: int
    pmin: float
    pmax: float
    cost: float


@dataclass(frozen=True)
class Renewable:
    name: str
    bus: int
    pmax: float
    kind: str


@dataclass(frozen=True)
class Step:
    index: int
    day: int
    hour: float
    duration: float
    resolution: str


@dataclass(frozen=True)
class MarketScenario:
    """Stage-2 result of conditional market simulation."""
    name: str
    probability: float
    export_appetite: float
    description: str


@dataclass(frozen=True)
class PhysicalForecastScenario:
    """Stage-3 trajectory generated by probabilistic local forecasting."""
    name: str
    parent_market: str
    conditional_probability: float
    load_factor_by_day: Tuple[float, ...]
    wind_factor_by_day: Tuple[float, ...]
    solar_factor_by_day: Tuple[float, ...]
    inflow_factor_by_day: Tuple[float, ...]
    dc_factor_by_day: Tuple[float, ...]
    failed_link: int
    failure_days: Tuple[int, ...]


@dataclass(frozen=True)
class JointScenario:
    """One leaf of the market-result / physical-error conditional tree."""
    market: MarketScenario
    physical: PhysicalForecastScenario

    @property
    def name(self) -> str:
        return f"{self.market.name}_{self.physical.name}"

    @property
    def probability(self) -> float:
        return self.market.probability * self.physical.conditional_probability


@dataclass(frozen=True)
class Package:
    name: str
    hydro_maint_start: int
    thermal_maint_start: int
    dr_reserve_mw: float
    d1_boundary_scale: float
    reserve_fraction: float
    terminal_water_mwh: float


@dataclass(frozen=True)
class ExternalObservation:
    """One synthetic observation available at the Yunnan boundary."""
    market_state: str
    load_block: str
    link: int
    clearing_price: float
    accepted_export_capacity: float


@dataclass(frozen=True)
class YunnanObservableProxy:
    """The complete external-information interface visible to the optimizer.

    It intentionally cannot carry external topology, unit, load, bid, or
    dispatch arrays. In production these envelopes would be fitted from public
    market results, Yunnan's own HVDC schedules, and equipment availability.
    """
    envelopes: Dict[str, Dict[str, List[float]]]

    def prices(self, market_state: str, load_block: str) -> Sequence[float]:
        return self.envelopes[market_state][f"{load_block}_price"]

    def capacities(self, market_state: str, load_block: str) -> Sequence[float]:
        return self.envelopes[market_state][f"{load_block}_capacity"]


@dataclass
class DispatchResult:
    objective_musd: float
    eens_gwh: float
    curtailment_gwh: float
    export_gwh: float
    export_value_musd: float
    hydro_gwh: float
    thermal_gwh: float
    dr_gwh: float
    reserve_shortfall_gwh: float
    terminal_water_gwh: float
    terminal_soc_gwh: float
    solve_seconds: float
    status: str


@dataclass
class SchemeResult:
    name: str
    package: str
    expected_objective_musd: float
    expected_eens_gwh: float
    eens_cvar90_gwh: float
    expected_curtailment_gwh: float
    expected_export_gwh: float
    expected_export_value_musd: float
    expected_hydro_gwh: float
    expected_dr_gwh: float
    expected_reserve_shortfall_gwh: float
    expected_terminal_water_gwh: float
    solve_seconds: float
    leaves: Dict[str, Dict[str, float]]


# Standard RTS-24 active loads at the system peak (MW).
RTS24_LOAD = np.array([
    108, 97, 180, 74, 71, 136, 125, 171, 175, 195, 0, 0,
    265, 194, 317, 100, 0, 333, 181, 128, 0, 0, 0, 0,
], dtype=float)

# Standard 38-branch RTS-24 skeleton. Ratings are the commonly used RTS
# normal limits; they are deliberately not strengthened after adding renewables.
RTS24_BRANCHES = [
    Branch(0, 1, .0146, 175), Branch(0, 2, .2253, 175),
    Branch(0, 4, .0907, 175), Branch(1, 3, .1356, 175),
    Branch(1, 5, .2050, 175), Branch(2, 8, .1271, 175),
    Branch(2, 23, .0840, 400), Branch(3, 8, .1110, 175),
    Branch(4, 9, .0940, 175), Branch(5, 9, .0642, 175),
    Branch(6, 7, .0652, 175), Branch(7, 8, .1762, 175),
    Branch(7, 9, .1762, 175), Branch(8, 10, .0840, 400),
    Branch(8, 11, .0840, 400), Branch(9, 10, .0840, 400),
    Branch(9, 11, .0840, 400), Branch(10, 12, .0488, 500),
    Branch(10, 13, .0426, 500), Branch(11, 12, .0488, 500),
    Branch(11, 22, .0985, 500), Branch(12, 22, .0884, 500),
    Branch(13, 15, .0594, 500), Branch(14, 15, .0172, 500),
    Branch(14, 20, .0249, 1000), Branch(14, 20, .0249, 1000),
    Branch(14, 23, .0529, 500), Branch(15, 16, .0263, 500),
    Branch(15, 18, .0234, 500), Branch(16, 17, .0143, 500),
    Branch(16, 21, .1069, 500), Branch(17, 20, .0132, 1000),
    Branch(18, 19, .0203, 1000), Branch(18, 19, .0203, 1000),
    Branch(19, 22, .0112, 1000), Branch(19, 22, .0112, 1000),
    Branch(20, 21, .0692, 500), Branch(22, 23, .0804, 500),
]

# Yunnan-oriented synthetic reclassification of the 33 RTS generating units.
# Hydro combines original large units at buses 13/18/21 and the six 50 MW
# hydro units at bus 22. Remaining units are aggregated by plant/bus as thermal.
HYDRO = [
    Generator("H13", 12, 0, 591, 3.0),
    Generator("H18", 17, 0, 400, 3.0),
    Generator("H21", 20, 0, 400, 3.0),
    Generator("H22", 21, 0, 300, 3.0),
]
THERMAL = [
    Generator("T1", 0, 38, 192, 54),
    Generator("T2", 1, 38, 192, 57),
    Generator("T7", 6, 75, 300, 46),
    Generator("T15", 14, 32, 215, 78),
    Generator("T16", 15, 30, 155, 72),
    Generator("T23", 22, 120, 660, 43),
]
RENEWABLES = [
    Renewable("W8", 7, 650, "wind"),
    Renewable("W15", 14, 550, "wind"),
    Renewable("W21", 20, 700, "wind"),
    Renewable("S3", 2, 400, "solar"),
    Renewable("S9", 8, 550, "solar"),
    Renewable("S23", 22, 450, "solar"),
]
DC_LOCAL_BUSES = [13, 15, 20, 22]  # RTS buses 14, 16, 21 and 23.
HIDDEN_ORACLE_BOUNDARY_BUSES = [7, 37, 67, 99]


def time_grid() -> List[Step]:
    steps: List[Step] = []
    for q in range(96):
        steps.append(Step(len(steps), 0, q / 4.0, .25, "15min"))
    for day in (1, 2):
        for hour in range(24):
            steps.append(Step(len(steps), day, float(hour), 1.0, "1h"))
    for day in range(3, 7):
        for hour in (4.0, 12.0, 20.0):
            steps.append(Step(len(steps), day, hour, 8.0, "block"))
    assert len(steps) == 156
    return steps


def _load_hidden_ieee118_truth() -> Tuple[List[Generator], List[Branch], np.ndarray]:
    """Load hidden benchmark truth; never call this from Yunnan optimization."""
    source = (ROOT / "src" / "scuc" / "case_builder.cpp").read_text()
    section = source[source.index("SCUCInput build_ieee118_case"):]

    gen_text = section[section.index("const GenSpec gens[]"):section.index("for (const auto& gs : gens)")]
    gens: List[Generator] = []
    for line in gen_text.splitlines():
        match = re.search(r'\{"(G\d+)",\s*(.*?)\},', line)
        if not match:
            continue
        values = [float(v.strip()) for v in match.group(2).split(",")]
        bus, pmin, pmax = int(values[0]), values[1], values[2]
        a_coeff, b_coeff = values[-2], values[-1]
        marginal_cost = b_coeff + a_coeff * pmax
        gens.append(Generator(match.group(1), bus, pmin, pmax, marginal_cost))

    branch_text = section[section.index("const BrSpec branches[]"):section.index("static_assert", section.index("const BrSpec branches[]"))]
    branches = [
        Branch(int(f), int(t), float(x), float(rating))
        for f, t, x, rating in re.findall(
            r"\{\s*(\d+),\s*(\d+),\s*([0-9.]+),\s*([0-9.]+)\s*\}", branch_text
        )
    ]

    load_text = section[section.index("const LoadSpec loads[]"):section.index("for (const auto& ls : loads)")]
    loads = np.zeros(118)
    for bus, value in re.findall(r"\{\s*(\d+),\s*([0-9.]+)\s*\}", load_text):
        loads[int(bus)] = float(value)
    # The local builder's explicit array contains 98 non-zero load buses even
    # though its header comment says 99; use the actual executable data.
    if (len(gens), len(branches), int(np.count_nonzero(loads))) != (54, 186, 98):
        raise RuntimeError(
            "IEEE-118 parser no longer matches case_builder.cpp: "
            f"gens={len(gens)}, branches={len(branches)}, loads={np.count_nonzero(loads)}"
        )
    return gens, branches, loads


def _network_matrix(n_bus: int, branches: Sequence[Branch]) -> np.ndarray:
    bbus = np.zeros((n_bus, n_bus))
    for line in branches:
        b = 100.0 / line.x
        bbus[line.f, line.f] += b
        bbus[line.t, line.t] += b
        bbus[line.f, line.t] -= b
        bbus[line.t, line.f] -= b
    return bbus


def _solve_hidden_ieee118_opf(
    gens: Sequence[Generator], branches: Sequence[Branch], base_load: np.ndarray,
    load_scale: float, availability: float, state_cost_scale: float,
    export_link: int | None,
) -> Tuple[float, float]:
    """Generate one observation inside the hidden external environment."""
    ng, nb = len(gens), 118
    has_q = export_link is not None
    n = ng + nb + nb + (1 if has_q else 0)  # generation, theta, shed, q
    c = np.zeros(n)
    for i, gen in enumerate(gens):
        c[i] = gen.cost * state_cost_scale
    c[ng + nb:ng + 2 * nb] = 10_000.0
    qidx = n - 1 if has_q else -1
    if has_q:
        c[qidx] = -10_000.0  # lexicographically maximize accepted injection.

    bounds: List[Tuple[float, float | None]] = []
    bounds.extend((0.0, gen.pmax * availability) for gen in gens)
    bounds.extend((0.0, 0.0) if b == 0 else (-math.pi, math.pi) for b in range(nb))
    bounds.extend((0.0, None) for _ in range(nb))
    if has_q:
        bounds.append((0.0, 800.0))

    bbus = _network_matrix(nb, branches)
    rows, cols, vals = [], [], []
    rhs = base_load * load_scale
    gens_by_bus: Dict[int, List[int]] = {}
    for i, gen in enumerate(gens):
        gens_by_bus.setdefault(gen.bus, []).append(i)
    for bus in range(nb):
        for i in gens_by_bus.get(bus, []):
            rows.append(bus); cols.append(i); vals.append(1.0)
        rows.append(bus); cols.append(ng + nb + bus); vals.append(1.0)
        for j, value in enumerate(bbus[bus]):
            if value:
                rows.append(bus); cols.append(ng + j); vals.append(-value)
        if has_q and bus == HIDDEN_ORACLE_BOUNDARY_BUSES[export_link]:
            rows.append(bus); cols.append(qidx); vals.append(1.0)
    aeq = coo_matrix((vals, (rows, cols)), shape=(nb, n)).tocsr()

    ur, uc, uv, ub = [], [], [], []
    for r, line in enumerate(branches):
        b = 100.0 / line.x
        for sign in (1.0, -1.0):
            ur.extend([len(ub), len(ub)])
            uc.extend([ng + line.f, ng + line.t])
            uv.extend([sign * b, -sign * b])
            ub.append(line.rating)
    aub = coo_matrix((uv, (ur, uc)), shape=(len(ub), n)).tocsr()
    result = linprog(c, A_ub=aub, b_ub=np.asarray(ub), A_eq=aeq,
                     b_eq=rhs, bounds=bounds, method="highs")
    if not result.success:
        raise RuntimeError(f"IEEE-118 calibration OPF failed: {result.message}")
    lmp_bus = HIDDEN_ORACLE_BOUNDARY_BUSES[export_link or 0]
    lmp = float(result.eqlin.marginals[lmp_bus])
    accepted = float(result.x[qidx]) if has_q else 0.0
    return lmp, accepted


def _generate_hidden_ieee118_observations() -> List[ExternalObservation]:
    """Use unobservable IEEE-118 truth only to generate boundary observations."""
    gens, branches, loads = _load_hidden_ieee118_truth()
    definitions = {
        "tight": (1.12, .78, 1.75),
        "loose": (.91, .92, 1.15),
    }
    profiles = {"valley": .78, "flat": .94, "peak": 1.08}
    observations: List[ExternalObservation] = []
    for state, (state_load, availability, cost_scale) in definitions.items():
        for label, shape in profiles.items():
            for link in range(4):
                price, capacity = _solve_hidden_ieee118_opf(
                    gens, branches, loads, state_load * shape,
                    availability, cost_scale, link,
                )
                # The local IEEE-118 bids are intentionally low synthetic test
                # bids. Add an explicit market-state scarcity premium instead
                # of misrepresenting their OPF marginal as a real regional LMP.
                observed_price = max(8.0, price) + (55.0 if state == "tight" else 18.0)
                # Individual transfer limits are made jointly conservative.
                observed_capacity = min(650.0, max(180.0, .62 * capacity))
                observations.append(ExternalObservation(
                    state, label, link, observed_price, observed_capacity
                ))
    return observations


def _fit_yunnan_observable_proxy(
    observations: Sequence[ExternalObservation],
) -> YunnanObservableProxy:
    """Fit the only external-data object accepted by the Yunnan optimizer."""
    envelopes: Dict[str, Dict[str, List[float]]] = {}
    for state in ("tight", "loose"):
        envelopes[state] = {}
        for label in ("valley", "flat", "peak"):
            selected = sorted(
                (obs for obs in observations
                 if obs.market_state == state and obs.load_block == label),
                key=lambda obs: obs.link,
            )
            if [obs.link for obs in selected] != list(range(4)):
                raise RuntimeError(f"incomplete observable envelope: {state}/{label}")
            envelopes[state][f"{label}_price"] = [obs.clearing_price for obs in selected]
            envelopes[state][f"{label}_capacity"] = [
                obs.accepted_export_capacity for obs in selected
            ]
    proxy = YunnanObservableProxy(envelopes)
    _validate_yunnan_information_boundary(proxy)
    return proxy


def _validate_yunnan_information_boundary(proxy: YunnanObservableProxy) -> None:
    """Reject accidental additions of hidden external data to planner input."""
    if set(vars(proxy)) != {"envelopes"}:
        raise RuntimeError("Yunnan proxy contains fields beyond observable envelopes")
    expected_keys = {
        f"{label}_{quantity}"
        for label in ("valley", "flat", "peak")
        for quantity in ("price", "capacity")
    }
    if set(proxy.envelopes) != {"tight", "loose"}:
        raise RuntimeError("Yunnan proxy must contain only inferred market states")
    for state, envelope in proxy.envelopes.items():
        if set(envelope) != expected_keys:
            raise RuntimeError(f"non-observable field in {state} external envelope")
        if any(len(values) != 4 or not np.all(np.isfinite(values))
               for values in envelope.values()):
            raise RuntimeError(f"invalid four-link observations in {state} envelope")


def build_benchmark_observable_proxy() -> YunnanObservableProxy:
    """Return public/boundary-like observations, never hidden IEEE-118 data."""
    observations = _generate_hidden_ieee118_observations()
    return _fit_yunnan_observable_proxy(observations)


def _shape_label(hour: float) -> str:
    if hour < 7 or hour >= 23:
        return "valley"
    if 17 <= hour < 23:
        return "peak"
    return "flat"


def _load_shape(hour: float) -> float:
    if hour < 6:
        return .70
    if hour < 10:
        return .82
    if hour < 17:
        return .88
    if hour < 22:
        return 1.0
    return .80


def _renewable_availability(unit: Renewable, step: Step, factor: float) -> float:
    day_factor = [1.00, .91, 1.10, 1.18, .86, .72, .68][step.day]
    if unit.kind == "solar":
        solar = max(0.0, math.sin(math.pi * (step.hour - 6.0) / 12.0))
        return min(unit.pmax, unit.pmax * solar * day_factor * factor)
    wind_shape = .48 + .16 * math.cos(2 * math.pi * (step.hour - 3.0) / 24.0)
    return min(unit.pmax, unit.pmax * wind_shape * day_factor * factor)


def _inflow_mw(day: int, factor: float) -> float:
    # Equivalent reservoir-energy inflow; MW over the represented duration.
    return [560, 520, 470, 430, 360, 310, 280][day] * factor


def market_simulation_scenarios() -> List[MarketScenario]:
    """Stage-2 states inferred only from Yunnan-observable information."""
    return [
        MarketScenario(
            "tight", .55, 1.00,
            "High receiving-side demand and strong Yunnan export acceptance",
        ),
        MarketScenario(
            "loose", .45, .15,
            "Low receiving-side demand and weak Yunnan export acceptance",
        ),
    ]


def physical_forecast_scenarios() -> List[PhysicalForecastScenario]:
    """Synthetic conditional trajectories standing in for calibrated forecasts.

    Production values must come from probabilistic inflow, wind, solar, load,
    and equipment-availability models. Seven entries correspond to D+1--D+7.
    """
    return [
        PhysicalForecastScenario(
            "dry", "tight", .40,
            (1.03, 1.04, 1.05, 1.055, 1.06, 1.07, 1.08),
            (.76, .73, .70, .68, .66, .63, .61),
            (.75, .73, .71, .69, .67, .65, .63),
            (.78, .74, .70, .68, .64, .60, .57),
            (1.00, .72, .72, .80, .85, .90, .90),
            2, (1, 2),
        ),
        PhysicalForecastScenario(
            "normal", "tight", .60,
            (1.005, 1.01, 1.015, 1.015, 1.02, 1.02, 1.025),
            (.97, .96, .95, .94, .93, .92, .91),
            (.98, .97, .96, .95, .94, .93, .92),
            (.95, .93, .91, .90, .89, .88, .87),
            (1.00,) * 7,
            -1, (),
        ),
        PhysicalForecastScenario(
            "normal", "loose", 4.0 / 9.0,
            (.995, .99, .985, .985, .98, .98, .975),
            (1.03, 1.04, 1.06, 1.07, 1.08, 1.08, 1.07),
            (1.02, 1.04, 1.05, 1.07, 1.08, 1.07, 1.06),
            (1.01, 1.03, 1.04, 1.05, 1.06, 1.07, 1.07),
            (1.00,) * 7,
            -1, (),
        ),
        PhysicalForecastScenario(
            "wet", "loose", 5.0 / 9.0,
            (.98, .97, .96, .955, .95, .945, .94),
            (1.12, 1.17, 1.23, 1.28, 1.30, 1.27, 1.22),
            (1.10, 1.16, 1.22, 1.28, 1.30, 1.28, 1.22),
            (1.12, 1.18, 1.24, 1.30, 1.34, 1.34, 1.30),
            (1.00, .88, .88, .90, .95, 1.00, 1.00),
            0, (1, 2),
        ),
    ]


def joint_scenarios() -> List[JointScenario]:
    markets = {scenario.name: scenario for scenario in market_simulation_scenarios()}
    result = [
        JointScenario(markets[physical.parent_market], physical)
        for physical in physical_forecast_scenarios()
    ]
    if abs(sum(scenario.probability for scenario in result) - 1.0) > 1e-12:
        raise RuntimeError("joint market/physical scenario probabilities do not sum to one")
    return result


def validate_uncertainty_models() -> None:
    markets = market_simulation_scenarios()
    physical = physical_forecast_scenarios()
    if abs(sum(s.probability for s in markets) - 1.0) > 1e-12:
        raise RuntimeError("market scenario probabilities do not sum to one")
    for market in markets:
        conditional = [s for s in physical if s.parent_market == market.name]
        if abs(sum(s.conditional_probability for s in conditional) - 1.0) > 1e-12:
            raise RuntimeError(f"conditional forecast probabilities fail for {market.name}")
    trajectory_fields = (
        "load_factor_by_day", "wind_factor_by_day", "solar_factor_by_day",
        "inflow_factor_by_day", "dc_factor_by_day",
    )
    for scenario in physical:
        for field in trajectory_fields:
            values = getattr(scenario, field)
            if len(values) != 7 or not np.all(np.isfinite(values)) or min(values) <= 0:
                raise RuntimeError(f"invalid {field} trajectory in {scenario.name}")


def summarize_market_simulation(
    package: Package, external_proxy: YunnanObservableProxy,
) -> List[Dict[str, float | str]]:
    steps = time_grid()
    near = np.asarray([step.day <= 2 for step in steps])
    summaries: List[Dict[str, float | str]] = []
    for market in market_simulation_scenarios():
        commitment, _, hydro_high, q_schedule = _market_template(
            steps, market, package, external_proxy
        )
        near_q = q_schedule[near].sum(axis=1)
        summaries.append({
            "market": market.name,
            "probability": market.probability,
            "mean_committed_thermal_units_d1_d3": float(commitment[near].sum(axis=1).mean()),
            "mean_active_hydro_zones_d1_d3": float((hydro_high[near] > 0).sum(axis=1).mean()),
            "mean_dc_schedule_mw_d1_d3": float(near_q.mean()),
            "p10_dc_schedule_mw_d1_d3": float(np.quantile(near_q, .10)),
            "p90_dc_schedule_mw_d1_d3": float(np.quantile(near_q, .90)),
        })
    return summaries


def candidate_packages() -> List[Package]:
    packages: List[Package] = []
    for start in range(1, 6):
        packages.extend([
            Package(f"economic_D{start+1}", start, max(1, start - 1), 0, 1.00, .05, 12_000),
            Package(f"economic_dr_D{start+1}", start, max(1, start - 1), 140, 1.00, .05, 12_000),
            Package(f"balanced_D{start+1}", start, min(5, start + 1), 80, .85, .09, 24_000),
            Package(f"secure_D{start+1}", start, min(5, start + 1), 140, .70, .13, 34_000),
        ])
    return packages


def package_first_stage_cost_musd(package: Package) -> float:
    """DR reservation payment over D+1--D+3; maintenance costs are common."""
    return 5.0 * package.dr_reserve_mw * 72.0 / 1e6


class LinearModel:
    def __init__(self) -> None:
        self.c: List[float] = []
        self.lb: List[float] = []
        self.ub: List[float | None] = []
        self.eq_rows: List[Dict[int, float]] = []
        self.eq_rhs: List[float] = []
        self.ineq_rows: List[Dict[int, float]] = []
        self.ineq_rhs: List[float] = []

    def var(self, lb: float = 0.0, ub: float | None = None, cost: float = 0.0) -> int:
        idx = len(self.c)
        self.c.append(cost); self.lb.append(lb); self.ub.append(ub)
        return idx

    def eq(self, terms: Mapping[int, float], rhs: float) -> None:
        self.eq_rows.append(dict(terms)); self.eq_rhs.append(rhs)

    def le(self, terms: Mapping[int, float], rhs: float) -> None:
        self.ineq_rows.append(dict(terms)); self.ineq_rhs.append(rhs)

    @staticmethod
    def _matrix(rows: Sequence[Mapping[int, float]], n: int):
        rr, cc, vv = [], [], []
        for r, row in enumerate(rows):
            for c, value in row.items():
                if value:
                    rr.append(r); cc.append(c); vv.append(value)
        return coo_matrix((vv, (rr, cc)), shape=(len(rows), n)).tocsr()

    def solve(self):
        n = len(self.c)
        return linprog(
            np.asarray(self.c),
            A_ub=self._matrix(self.ineq_rows, n), b_ub=np.asarray(self.ineq_rhs),
            A_eq=self._matrix(self.eq_rows, n), b_eq=np.asarray(self.eq_rhs),
            bounds=list(zip(self.lb, self.ub)), method="highs",
            options={"presolve": True},
        )


def _add(terms: Dict[int, float], idx: int, value: float) -> None:
    terms[idx] = terms.get(idx, 0.0) + value


def _market_template(
    steps: Sequence[Step], market: MarketScenario, package: Package,
    external_proxy: YunnanObservableProxy,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Create a market-scenario SCUC/zone/DC schedule template."""
    nt = len(steps)
    commitment = np.zeros((nt, len(THERMAL)))
    hydro_low = np.zeros((nt, len(HYDRO)))
    hydro_high = np.zeros((nt, len(HYDRO)))
    q_schedule = np.zeros((nt, 4))
    merit = sorted(range(len(THERMAL)), key=lambda g: THERMAL[g].cost)
    # In the loose state the receiving system has limited appetite for Yunnan
    # exports even though the physical DC equipment remains available.
    market_export = market.export_appetite
    for j, step in enumerate(steps):
        label = _shape_label(step.hour)
        caps = np.asarray(external_proxy.capacities(market.name, label))
        boundary = package.d1_boundary_scale if step.day == 0 else min(1.0, package.d1_boundary_scale + .10)
        q_schedule[j] = caps * market_export * boundary
        forecast_load = RTS24_LOAD.sum() * _load_shape(step.hour) * [1, 1.02, 1.05, 1, .98, 1.04, 1.08][step.day]
        forecast_ren = sum(_renewable_availability(r, step, 1.0) for r in RENEWABLES)
        required = max(0.0, forecast_load + q_schedule[j].sum() - .82 * forecast_ren - .58 * sum(h.pmax for h in HYDRO))
        capacity = 0.0
        for g in merit:
            commitment[j, g] = 1.0
            capacity += THERMAL[g].pmax
            if capacity >= required * 1.10:
                break
        hydro_need = max(0.0, forecast_load + q_schedule[j].sum() - .75 * forecast_ren - .65 * capacity)
        for h, plant in sorted(enumerate(HYDRO), key=lambda item: -item[1].pmax):
            if hydro_need > .46 * plant.pmax:
                hydro_low[j, h], hydro_high[j, h] = .60, 1.00
                hydro_need -= .75 * plant.pmax
            elif hydro_need > 1.0:
                hydro_low[j, h], hydro_high[j, h] = .15, .45
                hydro_need -= .30 * plant.pmax
            else:
                hydro_low[j, h], hydro_high[j, h] = 0.0, .45
    return commitment, hydro_low, hydro_high, q_schedule


def solve_dispatch(
    selected_steps: Sequence[Step], leaf: JointScenario, package: Package,
    external_proxy: YunnanObservableProxy,
    initial_water_mwh: float = 52_000.0, initial_soc_mwh: float = 750.0,
    enforce_terminal: bool = True,
) -> DispatchResult:
    start_clock = time.perf_counter()
    model = LinearModel()
    nt = len(selected_steps)
    full_steps = time_grid()
    commit_all, hlow_all, hhigh_all, qsched_all = _market_template(
        full_steps, leaf.market, package, external_proxy
    )
    indices = [step.index for step in selected_steps]
    commit, hlow, hhigh, qsched = commit_all[indices], hlow_all[indices], hhigh_all[indices], qsched_all[indices]
    bbus = _network_matrix(24, RTS24_BRANCHES)

    thermal = np.empty((nt, len(THERMAL)), dtype=int)
    hydro = np.empty((nt, len(HYDRO)), dtype=int)
    vibration_slack = np.empty((nt, len(HYDRO)), dtype=int)
    renewable = np.empty((nt, len(RENEWABLES)), dtype=int)
    charge = np.empty(nt, dtype=int); discharge = np.empty(nt, dtype=int)
    soc = np.empty(nt, dtype=int); water = np.empty(nt, dtype=int); spill = np.empty(nt, dtype=int)
    dc = np.empty((nt, 4), dtype=int); devp = np.empty((nt, 4), dtype=int); devn = np.empty((nt, 4), dtype=int)
    reserve_short = np.empty(nt, dtype=int)
    theta: Dict[Tuple[int, int], int] = {}
    shed: Dict[Tuple[int, int], int] = {}
    dr = np.full(3, -1, dtype=int)

    for day in range(3):
        if any(step.day == day for step in selected_steps):
            dr[day] = model.var(0, package.dr_reserve_mw, 38.0 * 4.0 / 1e6)

    for j, step in enumerate(selected_steps):
        dt = step.duration
        thermal_out = step.day == package.thermal_maint_start
        for g, plant in enumerate(THERMAL):
            online = bool(commit[j, g]) and not (thermal_out and plant.name == "T23")
            thermal[j, g] = model.var(
                plant.pmin if online else 0.0,
                plant.pmax if online else 0.0,
                dt * plant.cost / 1e6,
            )
        hydro_out = package.hydro_maint_start <= step.day < package.hydro_maint_start + 2
        for h, plant in enumerate(HYDRO):
            derate = 260.0 if hydro_out and plant.name == "H13" else 0.0
            available = max(0.0, plant.pmax - derate)
            lower = min(available, hlow[j, h] * plant.pmax)
            upper = min(available, hhigh[j, h] * plant.pmax)
            hydro[j, h] = model.var(0.0, max(lower, upper), dt * plant.cost / 1e6)
            vibration_slack[j, h] = model.var(0.0, None, dt * 1_200.0 / 1e6)
            # Reliability redispatch may leave the reserve-market stable zone,
            # but it is explicitly measured and strongly penalized.
            model.le({hydro[j, h]: -1.0, vibration_slack[j, h]: -1.0}, -lower)
        for r, unit in enumerate(RENEWABLES):
            factor = (
                leaf.physical.solar_factor_by_day[step.day]
                if unit.kind == "solar"
                else leaf.physical.wind_factor_by_day[step.day]
            )
            avail = _renewable_availability(unit, step, factor)
            renewable[j, r] = model.var(0, avail, -dt * 210.0 / 1e6)
        charge[j] = model.var(0, 250, dt * 1.5 / 1e6)
        discharge[j] = model.var(0, 250, dt * 4.0 / 1e6)
        soc[j] = model.var(150, 1_500)
        water[j] = model.var(0, 82_000)
        spill[j] = model.var(0, None, dt * 25.0 / 1e6)
        reserve_short[j] = model.var(0, None, dt * 5_000.0 / 1e6)

        label = _shape_label(step.hour)
        prices = np.asarray(external_proxy.prices(leaf.market.name, label))
        caps = (
            np.asarray(external_proxy.capacities(leaf.market.name, label))
            * leaf.physical.dc_factor_by_day[step.day]
        )
        for k in range(4):
            if leaf.physical.failed_link == k and step.day in leaf.physical.failure_days:
                caps[k] *= .10
            boundary = package.d1_boundary_scale if step.day == 0 else min(1.0, package.d1_boundary_scale + .10)
            cap = caps[k] * boundary
            dc[j, k] = model.var(0, cap, -dt * prices[k] / 1e6)
            if leaf.market.name == "loose":
                adjustment_band = 40.0 if step.day <= 2 else 70.0
            else:
                adjustment_band = 120.0 if step.day <= 2 else 180.0
            devp[j, k] = model.var(0, adjustment_band, dt * 18.0 / 1e6)
            scheduled = min(qsched[j, k], cap)
            # Export can always be reduced for reliability, but increasing it
            # after market clearing is limited by the declared adjustment band.
            devn[j, k] = model.var(0, scheduled, dt * 18.0 / 1e6)
            model.eq({dc[j, k]: 1, devp[j, k]: -1, devn[j, k]: 1}, scheduled)

        if step.day <= 2:
            for bus in range(24):
                theta[j, bus] = model.var(0, 0) if bus == 12 else model.var(-math.pi, math.pi)
                shed[j, bus] = model.var(0, None, dt * 10_000.0 / 1e6)
        else:
            shed[j, -1] = model.var(0, None, dt * 10_000.0 / 1e6)

    for j, step in enumerate(selected_steps):
        dt = step.duration
        inflow = _inflow_mw(
            step.day, leaf.physical.inflow_factor_by_day[step.day]
        ) * dt
        water_terms = {water[j]: 1.0, spill[j]: 1.0}
        for idx in hydro[j]:
            _add(water_terms, idx, dt)
        if j == 0:
            model.eq(water_terms, initial_water_mwh + inflow)
        else:
            _add(water_terms, water[j - 1], -1.0)
            model.eq(water_terms, inflow)

        soc_terms = {soc[j]: 1.0, charge[j]: -dt * .94, discharge[j]: dt / .94}
        if j == 0:
            model.eq(soc_terms, initial_soc_mwh)
        else:
            _add(soc_terms, soc[j - 1], -1.0)
            model.eq(soc_terms, 0.0)

        if j > 0:
            elapsed = max(.25, .5 * (selected_steps[j - 1].duration + dt))
            for g, plant in enumerate(THERMAL):
                current_online = model.ub[thermal[j, g]] != 0
                previous_online = model.ub[thermal[j - 1, g]] != 0
                if current_online and previous_online:
                    ramp = max(40.0, .45 * plant.pmax) * elapsed
                    model.le({thermal[j, g]: 1, thermal[j - 1, g]: -1}, ramp)
                    model.le({thermal[j - 1, g]: 1, thermal[j, g]: -1}, ramp)
            for k in range(4):
                model.le({dc[j, k]: 1, dc[j - 1, k]: -1}, 260 * elapsed)
                model.le({dc[j - 1, k]: 1, dc[j, k]: -1}, 260 * elapsed)

        load_multiplier = (
            _load_shape(step.hour)
            * [1, 1.02, 1.05, 1, .98, 1.04, 1.08][step.day]
            * leaf.physical.load_factor_by_day[step.day]
        )
        dr_adjust = 0.0
        if step.day <= 2 and dr[step.day] >= 0:
            if 10 <= step.hour < 14:
                dr_adjust = 1.0
            elif 18 <= step.hour < 22:
                dr_adjust = -1.0

        if step.day <= 2:
            for bus in range(24):
                terms: Dict[int, float] = {shed[j, bus]: 1.0}
                for g, plant in enumerate(THERMAL):
                    if plant.bus == bus: _add(terms, thermal[j, g], 1.0)
                for h, plant in enumerate(HYDRO):
                    if plant.bus == bus: _add(terms, hydro[j, h], 1.0)
                for r, unit in enumerate(RENEWABLES):
                    if unit.bus == bus: _add(terms, renewable[j, r], 1.0)
                if bus == 14:
                    _add(terms, discharge[j], 1.0); _add(terms, charge[j], -1.0)
                for k, dc_bus in enumerate(DC_LOCAL_BUSES):
                    if dc_bus == bus: _add(terms, dc[j, k], -1.0)
                if dr_adjust and RTS24_LOAD.sum() > 0:
                    _add(terms, dr[step.day], -dr_adjust * RTS24_LOAD[bus] / RTS24_LOAD.sum())
                for other, value in enumerate(bbus[bus]):
                    if value: _add(terms, theta[j, other], -value)
                model.eq(terms, RTS24_LOAD[bus] * load_multiplier)
            for line in RTS24_BRANCHES:
                b = 100.0 / line.x
                model.le({theta[j, line.f]: b, theta[j, line.t]: -b}, line.rating)
                model.le({theta[j, line.f]: -b, theta[j, line.t]: b}, line.rating)
        else:
            terms = {shed[j, -1]: 1.0, discharge[j]: 1.0, charge[j]: -1.0}
            for idx in thermal[j]: _add(terms, idx, 1.0)
            for idx in hydro[j]: _add(terms, idx, 1.0)
            for idx in renewable[j]: _add(terms, idx, 1.0)
            for idx in dc[j]: _add(terms, idx, -1.0)
            model.eq(terms, RTS24_LOAD.sum() * load_multiplier)

        if step.day <= 2:
            reserve_terms = {reserve_short[j]: -1.0, discharge[j]: 1.0}
            available_headroom = 250.0
            for g, plant in enumerate(THERMAL):
                if commit[j, g] and not (step.day == package.thermal_maint_start and plant.name == "T23"):
                    _add(reserve_terms, thermal[j, g], 1.0)
                    available_headroom += plant.pmax
            for h, plant in enumerate(HYDRO):
                _add(reserve_terms, hydro[j, h], 1.0)
                hydro_out = package.hydro_maint_start <= step.day < package.hydro_maint_start + 2
                cap = plant.pmax - (260.0 if hydro_out and plant.name == "H13" else 0.0)
                available_headroom += min(cap, hhigh[j, h] * plant.pmax)
            reserve_req = package.reserve_fraction * RTS24_LOAD.sum() * load_multiplier
            model.le(reserve_terms, available_headroom - reserve_req)

    if enforce_terminal:
        model.le({water[-1]: -1.0}, -package.terminal_water_mwh)
        model.le({soc[-1]: -1.0}, -750.0)

    result = model.solve()
    elapsed = time.perf_counter() - start_clock
    if not result.success:
        return DispatchResult(1e9, 1e6, 1e6, 0, 0, 0, 0, 0, 1e6, 0, 0, elapsed, result.message)

    x = result.x
    energy = lambda idxs: sum(selected_steps[j].duration * x[idx] for j, idx in idxs)
    shed_energy = 0.0
    for j, step in enumerate(selected_steps):
        buses = range(24) if step.day <= 2 else (-1,)
        shed_energy += step.duration * sum(x[shed[j, b]] for b in buses)
    renewable_avail = sum(
        step.duration * sum(
            _renewable_availability(
                r, step,
                (leaf.physical.solar_factor_by_day[step.day]
                 if r.kind == "solar"
                 else leaf.physical.wind_factor_by_day[step.day]),
            )
            for r in RENEWABLES
        )
        for step in selected_steps
    )
    renewable_used = sum(step.duration * sum(x[idx] for idx in renewable[j]) for j, step in enumerate(selected_steps))
    export_energy = sum(step.duration * sum(x[idx] for idx in dc[j]) for j, step in enumerate(selected_steps))
    export_value = 0.0
    for j, step in enumerate(selected_steps):
        prices = external_proxy.prices(leaf.market.name, _shape_label(step.hour))
        export_value += step.duration * sum(prices[k] * x[dc[j, k]] for k in range(4))
    hydro_energy = sum(step.duration * sum(x[idx] for idx in hydro[j]) for j, step in enumerate(selected_steps))
    thermal_energy = sum(step.duration * sum(x[idx] for idx in thermal[j]) for j, step in enumerate(selected_steps))
    dr_energy = sum(4.0 * x[idx] for idx in dr if idx >= 0)
    reserve_energy = sum(step.duration * x[reserve_short[j]] for j, step in enumerate(selected_steps))
    return DispatchResult(
        result.fun, shed_energy / 1000, (renewable_avail - renewable_used) / 1000,
        export_energy / 1000, export_value / 1e6, hydro_energy / 1000,
        thermal_energy / 1000, dr_energy / 1000, reserve_energy / 1000,
        x[water[-1]] / 1000, x[soc[-1]] / 1000, elapsed, "optimal",
    )


def _cvar(values: Sequence[float], probabilities: Sequence[float], alpha: float) -> float:
    order = np.argsort(values)
    remaining = 1.0 - alpha
    total = 0.0
    for idx in reversed(order):
        take = min(remaining, probabilities[idx])
        total += take * values[idx]
        remaining -= take
        if remaining <= 1e-12:
            break
    return total / (1.0 - alpha)


def aggregate_scheme(name: str, package: Package, results: Mapping[str, DispatchResult]) -> SchemeResult:
    all_leaves = joint_scenarios()
    probabilities = np.asarray([leaf.probability for leaf in all_leaves])
    def expected(field: str) -> float:
        return float(sum(leaf.probability * getattr(results[leaf.name], field) for leaf in all_leaves))
    return SchemeResult(
        name, package.name, expected("objective_musd"), expected("eens_gwh"),
        _cvar([results[l.name].eens_gwh for l in all_leaves], probabilities, .90),
        expected("curtailment_gwh"), expected("export_gwh"),
        expected("export_value_musd"), expected("hydro_gwh"), expected("dr_gwh"),
        expected("reserve_shortfall_gwh"), expected("terminal_water_gwh"),
        sum(r.solve_seconds for r in results.values()),
        {key: {k: v for k, v in asdict(value).items() if isinstance(v, (float, int))}
         for key, value in results.items()},
    )


def evaluate_package(
    package: Package, external_proxy: YunnanObservableProxy,
    selected_leaves: Iterable[JointScenario] | None = None,
):
    target = list(selected_leaves or joint_scenarios())
    results = {
        leaf.name: solve_dispatch(time_grid(), leaf, package, external_proxy)
        for leaf in target
    }
    first_stage_cost = package_first_stage_cost_musd(package)
    for result in results.values():
        result.objective_musd += first_stage_cost
    return results


def rolling_baseline(external_proxy: YunnanObservableProxy) -> SchemeResult:
    package = Package("rolling_DA", 1, 1, 0, 1.0, .04, 0)
    leaf_results: Dict[str, DispatchResult] = {}
    grid = time_grid()
    for leaf in joint_scenarios():
        water, soc = 52_000.0, 750.0
        totals = np.zeros(11)
        status = "optimal"
        for day in range(7):
            result = solve_dispatch([s for s in grid if s.day == day], leaf, package, external_proxy,
                                    water, soc, enforce_terminal=False)
            values = [result.objective_musd, result.eens_gwh, result.curtailment_gwh,
                      result.export_gwh, result.export_value_musd, result.hydro_gwh,
                      result.thermal_gwh, result.dr_gwh, result.reserve_shortfall_gwh,
                      result.solve_seconds]
            totals[:10] += values
            water, soc = result.terminal_water_gwh * 1000, result.terminal_soc_gwh * 1000
            status = result.status if result.status != "optimal" else status
        leaf_results[leaf.name] = DispatchResult(
            *totals[:9], water / 1000, soc / 1000, totals[9], status
        )
    return aggregate_scheme("逐日滚动基线", package, leaf_results)


def choose_and_evaluate(external_proxy: YunnanObservableProxy, quick: bool = False):
    packages = candidate_packages()
    if quick:
        packages = [p for p in packages if p.hydro_maint_start in (2, 4)]
    scenarios = joint_scenarios()
    central = next(leaf for leaf in scenarios if leaf.name == "tight_normal")
    deterministic_scores = []
    stochastic_scores = []
    package_results: Dict[str, Dict[str, DispatchResult]] = {}
    package_summaries: List[Dict[str, float | str | int]] = []
    clock = time.perf_counter()
    for i, package in enumerate(packages, 1):
        results = evaluate_package(package, external_proxy)
        package_results[package.name] = results
        deterministic_scores.append((results[central.name].objective_musd, package))
        expected_objective = sum(
            scenario.probability * results[scenario.name].objective_musd
            for scenario in scenarios
        )
        expected_eens = sum(
            scenario.probability * results[scenario.name].eens_gwh
            for scenario in scenarios
        )
        expected_curtailment = sum(
            scenario.probability * results[scenario.name].curtailment_gwh
            for scenario in scenarios
        )
        expected_reserve_shortfall = sum(
            scenario.probability * results[scenario.name].reserve_shortfall_gwh
            for scenario in scenarios
        )
        probabilities = [scenario.probability for scenario in scenarios]
        eens_cvar90 = _cvar(
            [results[s.name].eens_gwh for s in scenarios], probabilities, .90
        )
        curtailment_cvar90 = _cvar(
            [results[s.name].curtailment_gwh for s in scenarios], probabilities, .90
        )
        risk_feasible = (
            eens_cvar90 <= EENS_CVAR90_LIMIT_GWH + 1e-9
            and curtailment_cvar90 <= CURTAILMENT_CVAR90_LIMIT_GWH + 1e-9
            and expected_reserve_shortfall
            <= EXPECTED_RESERVE_SHORTFALL_LIMIT_GWH + 1e-9
        )
        # Lexicographic safety: reject risk-budget violations before comparing
        # expected economic objectives among risk-feasible packages.
        stochastic_scores.append((
            (0 if risk_feasible else 1, eens_cvar90, expected_objective), package
        ))
        package_summaries.append({
            "package": package.name,
            "hydro_maint_start_day": package.hydro_maint_start + 1,
            "thermal_maint_start_day": package.thermal_maint_start + 1,
            "dr_reserve_mw": package.dr_reserve_mw,
            "d1_boundary_scale": package.d1_boundary_scale,
            "reserve_fraction": package.reserve_fraction,
            "terminal_water_gwh": package.terminal_water_mwh / 1000.0,
            "central_objective_musd": results[central.name].objective_musd,
            "expected_objective_musd": expected_objective,
            "expected_eens_gwh": expected_eens,
            "eens_cvar90_gwh": eens_cvar90,
            "expected_curtailment_gwh": expected_curtailment,
            "curtailment_cvar90_gwh": curtailment_cvar90,
            "expected_reserve_shortfall_gwh": expected_reserve_shortfall,
            "risk_feasible": bool(risk_feasible),
            "expected_export_gwh": sum(
                scenario.probability * results[scenario.name].export_gwh
                for scenario in scenarios
            ),
        })
        print(f"  package {i:02d}/{len(packages)} {package.name:18s} "
              f"E[obj]={expected_objective:8.3f} M$", flush=True)
    decomposition_seconds = time.perf_counter() - clock
    det_package = min(deterministic_scores, key=lambda item: item[0])[1]
    sto_package = min(stochastic_scores, key=lambda item: item[0])[1]
    det = aggregate_scheme("确定性周前瞻", det_package, package_results[det_package.name])
    sto = aggregate_scheme("随机周前瞻", sto_package, package_results[sto_package.name])
    lp_solve_seconds = sum(
        result.solve_seconds
        for results in package_results.values()
        for result in results.values()
    )
    return (
        det, sto, decomposition_seconds, lp_solve_seconds,
        len(packages) * len(scenarios), package_summaries,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--quick", action="store_true", help="evaluate eight rather than twenty packages")
    parser.add_argument("--output", type=Path, default=RESULTS_PATH)
    args = parser.parse_args()

    print("Generating synthetic boundary observations in a hidden IEEE-118 environment ...")
    validate_uncertainty_models()
    external_proxy = build_benchmark_observable_proxy()
    print("Yunnan optimizer receives only prices and four HVDC acceptance envelopes.")
    print("Solving rolling day-ahead baseline ...")
    baseline = rolling_baseline(external_proxy)
    print("Evaluating maintenance/boundary/DR packages by scenario decomposition ...")
    (deterministic, stochastic, decomposition_seconds, lp_solve_seconds,
     subproblems, package_summaries) = choose_and_evaluate(external_proxy, args.quick)
    if stochastic.expected_eens_gwh > baseline.expected_eens_gwh + 1e-8:
        raise RuntimeError("week-ahead solution unexpectedly increases expected EENS")
    if any(scheme.expected_terminal_water_gwh < -1e-8 for scheme in (baseline, deterministic, stochastic)):
        raise RuntimeError("negative terminal water indicates an energy-balance error")
    selected_package = next(
        package for package in candidate_packages() if package.name == stochastic.package
    )

    payload = {
        "case": {
            "time_steps": 156, "d1_15min": 96, "d2_d3_hourly": 48,
            "d4_d7_blocks": 12, "local_buses": 24, "local_branches": 38,
            "dc_links": 4, "scenario_leaves": 4,
        },
        "information_boundary": {
            "jurisdiction": "Yunnan provincial dispatch",
            "planner_observes": [
                "Yunnan RTS-24 resources and network",
                "regional market-state labels inferred from public/history data",
                "published historical boundary prices and forecast intervals",
                "Yunnan's historical HVDC schedules and fitted acceptance envelopes",
                "Yunnan-side HVDC equipment availability",
            ],
            "planner_does_not_observe": [
                "other-province buses and branches",
                "other-province generators, loads, bids, and unit status",
                "other-province dispatch and reserve decisions",
            ],
            "ieee118_role": "hidden synthetic-observation generator; not an optimizer input",
        },
        "hidden_benchmark_environment": {
            "system": "IEEE-118", "buses": 118, "branches": 186,
            "exported_to_planner": False,
        },
        "observable_external_proxy": external_proxy.envelopes,
        "uncertainty_quantification": {
            "calibration_status": "synthetic benchmark; empirical calibration required",
            "physical_method": "probabilistic forecast trajectories",
            "market_method": "conditional reduced market simulation",
            "market_scenarios": [asdict(s) for s in market_simulation_scenarios()],
            "physical_scenarios": [asdict(s) for s in physical_forecast_scenarios()],
            "joint_tree": [
                {
                    "leaf": scenario.name,
                    "market": scenario.market.name,
                    "physical": scenario.physical.name,
                    "market_probability": scenario.market.probability,
                    "conditional_probability": scenario.physical.conditional_probability,
                    "joint_probability": scenario.probability,
                }
                for scenario in joint_scenarios()
            ],
        },
        "selected_market_simulation_summary": summarize_market_simulation(
            selected_package, external_proxy
        ),
        "algorithm": {
            "method": "finite-package logic decomposition with independent LP recourse",
            "lp_subproblems": subproblems,
            "candidate_set_gap": 0.0,
            "sum_lp_solve_seconds": lp_solve_seconds,
            "wall_seconds": decomposition_seconds,
            "risk_budgets": {
                "eens_cvar90_gwh": EENS_CVAR90_LIMIT_GWH,
                "curtailment_cvar90_gwh": CURTAILMENT_CVAR90_LIMIT_GWH,
                "expected_reserve_shortfall_gwh": EXPECTED_RESERVE_SHORTFALL_LIMIT_GWH,
            },
            "selection_rule": "risk-feasible first, then minimum expected objective",
        },
        "package_evaluations": package_summaries,
        "schemes": [asdict(baseline), asdict(deterministic), asdict(stochastic)],
        "disclaimer": "Synthetic Yunnan-oriented modification; mechanism benchmark, not an empirical forecast.",
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")

    print("\nExpected results")
    print(f"{'scheme':<18} {'EENS/GWh':>10} {'curt/GWh':>10} {'export/GWh':>12} {'water/GWh':>11} {'obj/M$':>10}")
    for scheme in (baseline, deterministic, stochastic):
        print(f"{scheme.name:<18} {scheme.expected_eens_gwh:10.3f} "
              f"{scheme.expected_curtailment_gwh:10.3f} {scheme.expected_export_gwh:12.3f} "
              f"{scheme.expected_terminal_water_gwh:11.3f} {scheme.expected_objective_musd:10.3f}")
    print(f"\nWrote {args.output}")


if __name__ == "__main__":
    main()
